"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Stage="Neu"|"Kontaktiert"|"Engaged"|"Termin"|"Angebot"|"Gewonnen"|"Verloren";
type Audit={scores?:{overall?:number;conversion?:number;trust?:number;seo?:number};sales?:{opportunitySummary?:string;emailHook?:string};auditedAt?:string};
type Lead={id:string;company:string;contact:string;email:string;phone:string;website:string;city:string;industry:string;stage:Stage;dealValue:number;notes:string;intentScore:number;websiteScore?:number;websiteAudit?:Audit;emailStatus?:string;energyScore?:number;videoUrl?:string};
type Step={waitDays:number;subject:string;body:string;variants?:Array<{label:string;subject:string;body:string}>};
type Campaign={id:string;name:string;audience:string;status:"Entwurf"|"Aktiv"|"Pausiert";dailyLimit:number;steps:Step[];sent:number;replies:number;positive:number;appointments:number;filters?:{industry?:string;city?:string;minWebsiteScore?:number;minIntentScore?:number;minEnergyScore?:number}};
type Mailbox={id:string;name:string;email:string;provider:"Google"|"Microsoft"|"SMTP";dailyLimit:number;sentToday:number;warmupDay:number;health:number;enabled:boolean;spf:boolean;dkim:boolean;dmarc:boolean};
type Settings={companyName:string;senderName:string;calendarUrl:string;timezone:string};
type Store={leads:Lead[];campaigns:Campaign[];mailboxes:Mailbox[];settings:Settings};
type Health={checks:Record<string,boolean>;configured:number;total:number;activeMailboxes?:number;coreReady?:boolean;outboundReady?:boolean;leadFinderReady?:boolean;aiReady?:boolean;videoReady?:boolean;ready:boolean};
type Section="cockpit"|"leads"|"campaigns"|"mailboxes"|"pipeline"|"analytics"|"settings";

const stages:Stage[]=["Neu","Kontaktiert","Engaged","Termin","Angebot","Gewonnen","Verloren"];
const nav:Array<{id:Section;label:string;icon:string}>=[
 {id:"cockpit",label:"Cockpit",icon:"◉"},{id:"leads",label:"Lead Radar",icon:"⌁"},{id:"campaigns",label:"Kampagnen",icon:"✦"},{id:"mailboxes",label:"Mailboxes",icon:"✉"},{id:"pipeline",label:"Pipeline",icon:"▦"},{id:"analytics",label:"Analytics",icon:"↗"},{id:"settings",label:"Setup",icon:"⚙"},
];
const starterCampaign:Campaign={id:"dg-starter",name:"Website Radar Outbound",audience:"KMU mit erkennbarem Website- und Neukundenpotenzial",status:"Entwurf",dailyLimit:150,sent:0,replies:0,positive:0,appointments:0,steps:[{waitDays:0,subject:"Kurze Idee zu {{company}}",body:"Hallo {{first_name}},\n\nich habe mir {{company}} kurz angesehen und eine kompakte Analyse vorbereitet: {{analysis_link}}\n\nDabei sind mir ein paar konkrete Hebel aufgefallen, die für mehr qualifizierte Anfragen interessant sein könnten.\n\nViele Grüße\n{{sender_name}}"},{waitDays:3,subject:"Re: Kurze Idee zu {{company}}",body:"Hallo {{first_name}}, kurze Nachfrage: Soll ich Ihnen die 2–3 wichtigsten Punkte aus der Analyse direkt schicken?"},{waitDays:7,subject:"Re: {{company}}",body:"Falls das Thema gerade keine Priorität hat, reicht ein kurzes 'später'."}]};
const fallback:Store={settings:{companyName:"Digitale Gewinner",senderName:"Raphael Hermann",calendarUrl:"",timezone:"Europe/Berlin"},leads:[],mailboxes:[],campaigns:[starterCampaign]};

function uid(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function money(value:number){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(value)}
function scoreClass(value:number){return value>=80?"score score-hot":value>=60?"score score-warm":"score"}
function migrate(raw:Store):Store{
 const settings={...fallback.settings,...(raw.settings||{})};
 if(settings.companyName==="Walkenhorst Energie")settings.companyName="Digitale Gewinner";
 if(settings.senderName==="Andreas Walkenhorst")settings.senderName="Raphael Hermann";
 const campaigns=(raw.campaigns||[]).map(c=>c.id==="starter"&&c.name==="Gewerbedächer BW"?starterCampaign:c);
 return{...fallback,...raw,settings,leads:raw.leads||[],mailboxes:raw.mailboxes||[],campaigns:campaigns.length?campaigns:[starterCampaign]};
}

export default function DigitaleGewinnerOutboundOS(){
 const [section,setSection]=useState<Section>("cockpit");
 const [store,setStore]=useState<Store>(fallback);
 const [health,setHealth]=useState<Health|null>(null);
 const [loaded,setLoaded]=useState(false);
 const [saving,setSaving]=useState(false);
 const [toast,setToast]=useState("");
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};

 async function refreshHealth(){try{const response=await fetch("/api/system/health");if(response.ok)setHealth(await response.json() as Health)}catch{}}
 useEffect(()=>{void(async()=>{let next=fallback;try{const response=await fetch("/api/state");if(response.ok){const json=await response.json() as {state?:Store};if(json.state)next=migrate(json.state)}}catch{}setStore(next);await refreshHealth();setLoaded(true)})()},[]);
 useEffect(()=>{if(!loaded)return;const timer=window.setTimeout(()=>{void(async()=>{setSaving(true);try{await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(store)})}finally{setSaving(false)}})()},650);return()=>window.clearTimeout(timer)},[store,loaded]);

 const activeMailboxes=useMemo(()=>store.mailboxes.filter(m=>m.enabled),[store.mailboxes]);
 const stats=useMemo(()=>({
  leads:store.leads.length,
  hot:store.leads.filter(l=>Math.max(l.websiteScore||0,l.intentScore||0,l.energyScore||0)>=80).length,
  pipeline:store.leads.filter(l=>!["Gewonnen","Verloren"].includes(l.stage)).reduce((sum,l)=>sum+(l.dealValue||0),0),
  appointments:store.leads.filter(l=>l.stage==="Termin").length,
  won:store.leads.filter(l=>l.stage==="Gewonnen").length,
  capacity:activeMailboxes.reduce((sum,m)=>sum+(m.dailyLimit||0),0),
  health:activeMailboxes.length?Math.round(activeMailboxes.reduce((sum,m)=>sum+(m.health||0),0)/activeMailboxes.length):0,
 }),[store.leads,activeMailboxes]);
 const hottest=useMemo(()=>[...store.leads].sort((a,b)=>Math.max(b.intentScore||0,b.websiteScore||0,b.energyScore||0)-Math.max(a.intentScore||0,a.websiteScore||0,a.energyScore||0)).slice(0,8),[store.leads]);

 function stageLead(id:string,stage:Stage){setStore(s=>({...s,leads:s.leads.map(l=>l.id===id?{...l,stage}:l)}))}
 async function verify(email:string){if(!email)return notify("Keine E-Mail vorhanden.");const response=await fetch("/api/email/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const json=await response.json() as {status?:string;error?:string};notify(response.ok?`E-Mail: ${json.status||"geprüft"}`:(json.error||"Prüfung fehlgeschlagen"))}

 async function addLead(event:FormEvent<HTMLFormElement>){
  event.preventDefault();const f=new FormData(event.currentTarget);const company=String(f.get("company")||"").trim();if(!company)return;
  const website=String(f.get("website")||"").trim();let email=String(f.get("email")||"").trim();let phone=String(f.get("phone")||"").trim();let websiteAudit:Audit|undefined;let websiteScore=0;let emailStatus="";
  try{
   if(website){const [enrichResponse,auditResponse]=await Promise.all([fetch("/api/leads/enrich",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({website})}),fetch("/api/website/audit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url:website,company})})]);if(enrichResponse.ok){const json=await enrichResponse.json() as {contact?:{email?:string;phone?:string}};email=email||String(json.contact?.email||"");phone=phone||String(json.contact?.phone||"")}if(auditResponse.ok){const json=await auditResponse.json() as {audit?:Audit};websiteAudit=json.audit;websiteScore=Number(json.audit?.scores?.overall||0)}}
   if(email){const verifyResponse=await fetch("/api/email/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});if(verifyResponse.ok){const json=await verifyResponse.json() as {status?:string};emailStatus=json.status||""}}
  }catch{}
  const lead:Lead={id:uid("lead"),company,contact:String(f.get("contact")||""),email,phone,website,city:String(f.get("city")||""),industry:String(f.get("industry")||""),stage:"Neu",dealValue:Number(f.get("dealValue")||0),notes:websiteAudit?.sales?.opportunitySummary?`Website Radar: ${websiteAudit.sales.opportunitySummary}`:"",intentScore:0,websiteScore,websiteAudit,emailStatus};
  setStore(s=>({...s,leads:[lead,...s.leads]}));event.currentTarget.reset();notify(`Lead gespeichert${websiteScore?` · Website Score ${websiteScore}`:""}${email?" · E-Mail vorhanden":" · E-Mail offen"}`);
 }

 async function aiCampaign(){const audience=window.prompt("Zielgruppe für die Kampagne?");if(!audience)return;const offer=window.prompt("Angebot / Nutzen?")||"Website- und Outbound-Analyse";const response=await fetch("/api/ai/campaign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({audience,offer,sender:store.settings.senderName})});const json=await response.json() as {name?:string;audience?:string;steps?:Step[];error?:string};if(!response.ok||!json.steps)return notify(json.error||"KI-Kampagne konnte nicht erstellt werden.");setStore(s=>({...s,campaigns:[{id:uid("campaign"),name:json.name||"KI Kampagne",audience:json.audience||audience,status:"Entwurf",dailyLimit:150,steps:json.steps,sent:0,replies:0,positive:0,appointments:0},...s.campaigns]}));notify("KI-Kampagne erstellt.")}
 async function launch(campaign:Campaign){const leads=store.leads.filter(l=>l.email&&!["Gewonnen","Verloren"].includes(l.stage));if(!leads.length)return notify("Keine versandfähigen Leads vorhanden.");if(!activeMailboxes.length)return notify("Keine aktive Mailbox vorhanden.");const response=await fetch("/api/campaigns/launch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({campaign,leads,mailboxes:store.mailboxes,senderName:store.settings.senderName})});const json=await response.json() as {queued?:number;skipped?:number;error?:string};if(!response.ok)return notify(json.error||"Kampagnenstart fehlgeschlagen.");setStore(s=>({...s,campaigns:s.campaigns.map(c=>c.id===campaign.id?{...c,status:"Aktiv"}:c)}));notify(`${json.queued||0} Schritte eingeplant · ${json.skipped||0} übersprungen`)}
 function addMailbox(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const email=String(f.get("email")||"").trim();if(!email.includes("@"))return notify("Gültige Mailbox-E-Mail fehlt.");setStore(s=>({...s,mailboxes:[...s.mailboxes,{id:String(f.get("id")||uid("mb")),name:String(f.get("name")||"Mailbox"),email,provider:String(f.get("provider")||"Google") as Mailbox["provider"],dailyLimit:5,sentToday:0,warmupDay:1,health:60,enabled:true,spf:false,dkim:false,dmarc:false}]}));event.currentTarget.reset();notify("Mailbox angelegt · Startlimit 5/Tag")}
 async function domainCheck(mailbox:Mailbox){const domain=mailbox.email.split("@")[1];const response=await fetch("/api/domain/health",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({domain})});const json=await response.json() as {spf?:boolean;dmarc?:boolean;score?:number;error?:string};if(!response.ok)return notify(json.error||"Domain Check fehlgeschlagen.");setStore(s=>({...s,mailboxes:s.mailboxes.map(m=>m.id===mailbox.id?{...m,spf:Boolean(json.spf),dmarc:Boolean(json.dmarc),health:Math.max(m.health,json.score||0)}:m)}));notify(`${domain}: SPF ${json.spf?"OK":"fehlt"} · DMARC ${json.dmarc?"OK":"fehlt"}`)}
 function ramp(id:string){setStore(s=>({...s,mailboxes:s.mailboxes.map(m=>{if(m.id!==id)return m;const day=m.warmupDay+1;const dailyLimit=day<4?5:day<7?10:day<11?15:day<15?20:day<19?25:30;return{...m,warmupDay:day,dailyLimit}})}))}
 function saveSettings(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setStore(s=>({...s,settings:{companyName:String(f.get("companyName")||"Digitale Gewinner"),senderName:String(f.get("senderName")||"Raphael Hermann"),calendarUrl:String(f.get("calendarUrl")||""),timezone:String(f.get("timezone")||"Europe/Berlin")}}));notify("Setup gespeichert.")}

 const metric=(label:string,value:string|number,sub:string)=><div className="metric"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>;
 const readiness=[
  ["Core",Boolean(health?.coreReady),"DB · Login · Secrets · Public URL"],
  ["Outbound",Boolean(health?.outboundReady),"Mailbox + Credentials + Versandkern"],
  ["Lead Finder",Boolean(health?.leadFinderReady),"Google Places"],
  ["KI",Boolean(health?.aiReady),"OpenAI Kampagnen"],
  ["Fake Loom",Boolean(health?.videoReady),"Video Renderer"],
 ] as const;

 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">DG</span><div><strong>Digitale Gewinner</strong><small>Outbound OS</small></div></div><nav>{nav.map(item=><button key={item.id} className={`nav-item ${section===item.id?"active":""}`} onClick={()=>setSection(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-foot"><i className="health-dot"/><span>{saving?"Speichert…":health?.ready?"Production ready":"Setup läuft"}</span><small>{health?`${health.configured}/${health.total} Checks`:"Readiness lädt"}</small></div></aside><section className="workspace"><header className="topbar"><div><small>DIGITALE GEWINNER · CUSTOMER ACQUISITION ENGINE</small><h1>{nav.find(item=>item.id===section)?.label}</h1></div><div className="top-actions"><span className="live-pill">● {health?.ready?"READY":"LIVE"}</span><div className="avatar">DG</div></div></header><div className="content">

 {section==="cockpit"&&<><div className="hero-grid"><div className="hero-card"><div><span className="eyebrow">REVENUE PRIORITY</span><h2>{stats.hot} Leads mit hohem Optimierungs- oder Kaufsignal.</h2><p>Unternehmen finden, öffentlich sichtbare Geschäftskontakte anreichern, Website analysieren, personalisieren, versenden und Antworten bis zum Abschluss verfolgen.</p></div><div className="hero-number">{stats.hot}<small>HOT LEADS</small></div></div><div className="capacity-card"><span>Versandkapazität</span><strong>{stats.capacity}/Tag</strong><div className="progress"><i style={{width:`${Math.min(100,stats.capacity/1.5)}%`}}/></div><small>{activeMailboxes.length} aktive Mailbox{activeMailboxes.length===1?"":"en"} · kontrollierte Tageslimits</small></div></div><div className="metric-grid">{metric("Leads",stats.leads,"im Radar")}{metric("Pipeline",money(stats.pipeline),"offen")}{metric("Termine",stats.appointments,"gebucht")}{metric("Gewonnen",stats.won,"Deals")}</div><div className="panel"><div className="panel-head"><div><h3>Hot Lead Queue</h3><p>Website Score und Intent kombiniert</p></div></div><div className="lead-list">{hottest.length?hottest.map(lead=>{const score=Math.max(lead.websiteScore||0,lead.intentScore||0,lead.energyScore||0);return <div className="lead-row" key={lead.id}><div><strong>{lead.company}</strong><small>{lead.city||"—"} · {lead.industry||"Branche offen"}</small></div><span className={scoreClass(score)}>{score}</span><span className={scoreClass(lead.intentScore||0)}>I {lead.intentScore||0}</span><select value={lead.stage} onChange={e=>stageLead(lead.id,e.target.value as Stage)}>{stages.map(stage=><option key={stage}>{stage}</option>)}</select></div>}):<div className="callout">Noch keine Leads. Nutze „Lead Finder“ oder „Website Radar“.</div>}</div></div></>}

 {section==="leads"&&<div className="two-col wide-left"><div className="panel"><div className="panel-head"><div><h3>Lead Intelligence</h3><p>Kontakt, Website Score, Intent und Pipeline</p></div></div><div className="table-wrap"><table><thead><tr><th>Unternehmen</th><th>E-Mail</th><th>Website</th><th>Intent</th><th>Stage</th><th></th></tr></thead><tbody>{store.leads.map(lead=><tr key={lead.id}><td><strong>{lead.company}</strong><small>{lead.city||"—"} · {lead.industry||"—"}</small></td><td>{lead.email||"—"}<small>{lead.emailStatus||""}</small></td><td><span className={scoreClass(lead.websiteScore||0)}>{lead.websiteScore||"—"}</span></td><td><span className={scoreClass(lead.intentScore||0)}>{lead.intentScore||0}</span></td><td><select value={lead.stage} onChange={e=>stageLead(lead.id,e.target.value as Stage)}>{stages.map(stage=><option key={stage}>{stage}</option>)}</select></td><td><button className="ghost" onClick={()=>void verify(lead.email)}>Verify</button></td></tr>)}</tbody></table></div></div><form className="panel form-panel" onSubmit={addLead}><div className="panel-head"><div><h3>Lead manuell anlegen</h3><p>Website wird automatisch analysiert und angereichert</p></div></div><label>Unternehmen<input name="company" required/></label><div className="split"><label>Kontakt<input name="contact"/></label><label>Stadt<input name="city"/></label></div><label>E-Mail<input name="email" type="email"/></label><label>Telefon<input name="phone"/></label><label>Website<input name="website" placeholder="https://..."/></label><label>Branche<input name="industry"/></label><label>Dealwert €<input name="dealValue" type="number" min="0"/></label><button className="primary">Anreichern & speichern</button></form></div>}

 {section==="campaigns"&&<div className="panel"><div className="panel-head"><div><h3>Campaign Engine</h3><p>Sequenzen · A/B/C · Segmentierung · Stop-on-Reply · Rotation</p></div><button className="ghost" onClick={()=>void aiCampaign()}>+ KI-Kampagne</button></div>{store.campaigns.map(campaign=><div className="campaign-card" key={campaign.id}><div className="campaign-head"><div><span className="eyebrow">{campaign.status.toUpperCase()}</span><h3>{campaign.name}</h3><p>{campaign.audience}</p></div><button className="ghost" onClick={()=>void launch(campaign)}>Starten</button></div><div className="campaign-metrics"><span><small>Schritte</small><b>{campaign.steps.length}</b></span><span><small>Limit/Tag</small><b>{campaign.dailyLimit}</b></span><span><small>Replies</small><b>{campaign.replies||0}</b></span><span><small>Termine</small><b>{campaign.appointments||0}</b></span></div><div className="sequence">{campaign.steps.map((step,index)=><div className="sequence-step" key={index}><span>{index+1}</span><div><strong>{index===0?"Start":`+${step.waitDays} Tage`}</strong><small>{step.subject}</small><p>{step.variants?.length?`${step.variants.length} Varianten`:"Standard"}</p></div></div>)}</div></div>)}</div>}

 {section==="mailboxes"&&<div className="two-col wide-left"><div className="panel"><div className="panel-head"><div><h3>Sender Infrastructure</h3><p>Gesunde Limits statt aggressivem Massenversand</p></div></div><div className="mailboxes">{store.mailboxes.length?store.mailboxes.map(mailbox=><div className="mailbox-card" key={mailbox.id}><div className="mailbox-top"><span className="mail-icon">✉</span><div><strong>{mailbox.email}</strong><small>{mailbox.provider} · Tag {mailbox.warmupDay} · {mailbox.dailyLimit}/Tag</small></div><button className="ghost" onClick={()=>ramp(mailbox.id)}>Ramp</button></div><div className="mail-health"><span>Health</span><b>{mailbox.health}%</b></div><div className="progress"><i style={{width:`${mailbox.health}%`}}/></div><div className="dns"><span className={mailbox.spf?"ok":""}>SPF</span><span className={mailbox.dmarc?"ok":""}>DMARC</span><button className="link-btn" onClick={()=>void domainCheck(mailbox)}>Domain prüfen</button></div></div>):<div className="callout">Noch keine Mailbox. Mailbox anlegen und anschließend Google/Microsoft OAuth oder SMTP im API-Tresor verbinden.</div>}</div></div><form className="panel form-panel" onSubmit={addMailbox}><div className="panel-head"><div><h3>Mailbox hinzufügen</h3><p>ID muss zu den Zugangsdaten passen</p></div></div><label>Credential-ID<input name="id" placeholder="mb-raphael"/></label><label>Absendername<input name="name" placeholder="Raphael"/></label><label>E-Mail<input name="email" type="email" required/></label><label>Provider<select name="provider"><option>Google</option><option>Microsoft</option><option>SMTP</option></select></label><button className="primary">Mailbox anlegen</button></form></div>}

 {section==="pipeline"&&<div className="panel"><div className="panel-head"><div><h3>Sales Pipeline</h3><p>Vom Erstkontakt bis zum gewonnenen Kunden</p></div></div><div className="kanban">{stages.map(stage=><div className="kanban-col" key={stage}><div className="kanban-title"><strong>{stage}</strong><span>{store.leads.filter(l=>l.stage===stage).length}</span></div>{store.leads.filter(l=>l.stage===stage).map(lead=><div className="deal-card" key={lead.id}><h4>{lead.company}</h4><p>{lead.contact||lead.email||"Kontakt offen"}</p><b>{money(lead.dealValue||0)}</b><select value={lead.stage} onChange={e=>stageLead(lead.id,e.target.value as Stage)}>{stages.map(item=><option key={item}>{item}</option>)}</select></div>)}</div>)}</div></div>}

 {section==="analytics"&&<><div className="metric-grid">{metric("Versandkapazität",stats.capacity,"E-Mails/Tag")}{metric("Hot Leads",stats.hot,"Priorität")}{metric("Termine",stats.appointments,"Pipeline")}{metric("Mailbox Health",`${stats.health}%`,"aktive Sender")}</div><div className="panel"><div className="panel-head"><div><h3>Production Readiness</h3><p>Keine grüne Ampel ohne den vollständigen Kern</p></div><button className="ghost" onClick={()=>void refreshHealth()}>Neu prüfen</button></div><div className="integration-list">{readiness.map(([label,ok,detail])=><div key={label}><span className={`integration-icon ${ok?"ok-bg":""}`}>{ok?"✓":"!"}</span><div><strong>{label}</strong><small>{detail}</small></div><span className={ok?"status-green":"status"}>{ok?"READY":"SETUP"}</span></div>)}</div></div></>}

 {section==="settings"&&<div className="two-col wide-left"><form key={`${store.settings.companyName}-${store.settings.senderName}-${store.settings.calendarUrl}`} className="panel form-panel" onSubmit={saveSettings}><div className="panel-head"><div><h3>Digitale Gewinner Setup</h3><p>Personalisierung und Termin-CTA</p></div></div><label>Unternehmen<input name="companyName" defaultValue={store.settings.companyName}/></label><label>Absendername<input name="senderName" defaultValue={store.settings.senderName}/></label><label>Kalender-URL<input name="calendarUrl" defaultValue={store.settings.calendarUrl} placeholder="https://cal.com/..."/></label><label>Zeitzone<input name="timezone" defaultValue={store.settings.timezone}/></label><button className="primary">Setup speichern</button></form><div className="panel"><div className="panel-head"><div><h3>Produktionsstatus</h3><p>Secrets bleiben serverseitig</p></div></div><div className="integration-list">{readiness.map(([label,ok,detail])=><div key={label}><span className={`integration-icon ${ok?"ok-bg":""}`}>{ok?"✓":"!"}</span><div><strong>{label}</strong><small>{detail}</small></div><span className={ok?"status-green":"status"}>{ok?"READY":"SETUP"}</span></div>)}</div><div className="callout">Pflicht für den Livebetrieb: Datenbank, Admin-/Encryption-Secrets, Public URL, Cron/Webhook Secret und mindestens eine korrekt verbundene Mailbox. Lead Finder, KI und Fake Loom werden separat als Capability geprüft.</div></div></div>}
 </div></section>{toast&&<div className="toast">{toast}</div>}</main>;
}
