"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Stage="Neu"|"Kontaktiert"|"Engaged"|"Termin"|"Angebot"|"Gewonnen"|"Verloren";
type Lead={id:string;company:string;contact:string;email:string;phone:string;website:string;city:string;industry:string;employees:number;roofArea:number;pvExisting:boolean;energyScore:number;intentScore:number;stage:Stage;dealValue:number;notes:string};
type Step={waitDays:number;subject:string;body:string};
type Campaign={id:string;name:string;audience:string;status:"Entwurf"|"Aktiv"|"Pausiert";dailyLimit:number;steps:Step[];sent:number;replies:number;positive:number;appointments:number};
type Mailbox={id:string;name:string;email:string;provider:"Google"|"Microsoft"|"SMTP";dailyLimit:number;sentToday:number;warmupDay:number;health:number;enabled:boolean;spf:boolean;dkim:boolean;dmarc:boolean};
type Store={leads:Lead[];campaigns:Campaign[];mailboxes:Mailbox[];settings:{companyName:string;senderName:string;calendarUrl:string;timezone:string}};
type Health={checks:Record<string,boolean>;configured:number;total:number;ready:boolean};
type Section="cockpit"|"leads"|"campaigns"|"mailboxes"|"pipeline"|"analytics"|"integrations";

const stages:Stage[]=["Neu","Kontaktiert","Engaged","Termin","Angebot","Gewonnen","Verloren"];
const nav:{id:Section;icon:string;label:string}[]=[{id:"cockpit",icon:"◉",label:"Cockpit"},{id:"leads",icon:"⌁",label:"Lead Radar"},{id:"campaigns",icon:"✦",label:"Kampagnen"},{id:"mailboxes",icon:"✉",label:"Mailboxes"},{id:"pipeline",icon:"▦",label:"Pipeline"},{id:"analytics",icon:"↗",label:"Analytics"},{id:"integrations",icon:"⚙",label:"Integrationen"}];
const fallback:Store={settings:{companyName:"Walkenhorst Energie",senderName:"Andreas Walkenhorst",calendarUrl:"",timezone:"Europe/Berlin"},leads:[],mailboxes:[],campaigns:[{id:"starter",name:"Gewerbedächer BW",audience:"Produktion & Logistik, 20–250 Mitarbeiter",status:"Entwurf",dailyLimit:150,sent:0,replies:0,positive:0,appointments:0,steps:[{waitDays:0,subject:"Kurze Frage zu {{company}}",body:"Hallo {{first_name}},\n\nich habe eine unverbindliche Voranalyse für {{company}} vorbereitet: {{analysis_link}}\n\nViele Grüße\n{{sender_name}}"},{waitDays:3,subject:"Re: Kurze Frage zu {{company}}",body:"Hallo {{first_name}}, ist das Thema für Sie grundsätzlich relevant?"},{waitDays:7,subject:"Re: {{company}}",body:"Falls es aktuell keine Priorität hat, reicht ein kurzes 'später'."}]}]};
function uid(p:string){return `${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function money(v:number){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(v)}
function scoreClass(v:number){return v>=85?"score score-hot":v>=65?"score score-warm":"score"}

export default function EnergyRadarLive(){
 const [section,setSection]=useState<Section>("cockpit");const [store,setStore]=useState<Store>(fallback);const [health,setHealth]=useState<Health|null>(null);const [toast,setToast]=useState("");const [loaded,setLoaded]=useState(false);const [saving,setSaving]=useState(false);
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2500)};
 useEffect(()=>{void(async()=>{try{const r=await fetch("/api/state");if(r.ok){const j=await r.json() as {state?:Store};if(j.state)setStore(j.state)}}catch{}try{const r=await fetch("/api/system/health");if(r.ok)setHealth(await r.json() as Health)}catch{}setLoaded(true)})()},[]);
 useEffect(()=>{if(!loaded)return;const t=window.setTimeout(()=>{void(async()=>{setSaving(true);try{await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(store)})}finally{setSaving(false)}})()},650);return()=>window.clearTimeout(t)},[store,loaded]);
 const stats=useMemo(()=>{const active=store.mailboxes.filter(m=>m.enabled);return{leads:store.leads.length,hot:store.leads.filter(l=>l.energyScore>=80||l.intentScore>=80).length,pipeline:store.leads.filter(l=>!["Gewonnen","Verloren"].includes(l.stage)).reduce((a,b)=>a+b.dealValue,0, ),capacity:active.reduce((a,b)=>a+b.dailyLimit,0),appointments:store.leads.filter(l=>l.stage==="Termin").length,health:active.length?Math.round(active.reduce((a,b)=>a+b.health,0)/active.length):0}},[store]);
 const hottest=useMemo(()=>[...store.leads].sort((a,b)=>(b.energyScore+b.intentScore)-(a.energyScore+a.intentScore)).slice(0,8),[store.leads]);
 function stageLead(id:string,stage:Stage){setStore(s=>({...s,leads:s.leads.map(l=>l.id===id?{...l,stage}:l)}))}
 async function addLead(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const input={industry:String(f.get("industry")||""),employees:Number(f.get("employees")||0),roofArea:Number(f.get("roofArea")||0),pvExisting:f.get("pvExisting")==="on"};let energyScore=50;try{const r=await fetch("/api/energy/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});if(r.ok)energyScore=((await r.json()) as {score:number}).score}catch{}const company=String(f.get("company")||"").trim();if(!company)return;const lead:Lead={id:uid("lead"),company,contact:String(f.get("contact")||""),email:String(f.get("email")||""),phone:String(f.get("phone")||""),website:String(f.get("website")||""),city:String(f.get("city")||""),industry:input.industry,employees:input.employees,roofArea:input.roofArea,pvExisting:input.pvExisting,energyScore,intentScore:0,stage:"Neu",dealValue:Number(f.get("dealValue")||0),notes:""};setStore(s=>({...s,leads:[lead,...s.leads]}));e.currentTarget.reset();notify(`Lead gespeichert · Energy Score ${energyScore}`)}
 async function verify(email:string){if(!email)return notify("Keine E-Mail vorhanden.");const r=await fetch("/api/email/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const j=await r.json() as {status?:string;error?:string};notify(r.ok?`E-Mail Status: ${j.status}`:(j.error||"Prüfung fehlgeschlagen"))}
 async function aiCampaign(){const audience=window.prompt("Zielgruppe?");if(!audience)return;const offer=window.prompt("Angebot / Nutzen?")||"Energie-Potenzialanalyse";const r=await fetch("/api/ai/campaign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({audience,offer,sender:store.settings.senderName})});const j=await r.json() as {name?:string;audience?:string;steps?:Step[];error?:string};if(!r.ok||!j.steps)return notify(j.error||"KI nicht verbunden.");setStore(s=>({...s,campaigns:[{id:uid("campaign"),name:j.name||"KI Kampagne",audience:j.audience||audience,status:"Entwurf",dailyLimit:150,steps:j.steps||[],sent:0,replies:0,positive:0,appointments:0},...s.campaigns]}));notify("KI-Kampagne erstellt.")}
 async function launch(c:Campaign){const leads=store.leads.filter(l=>l.email&&!["Gewonnen","Verloren"].includes(l.stage));const r=await fetch("/api/campaigns/launch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({campaign:c,leads,mailboxes:store.mailboxes,senderName:store.settings.senderName})});const j=await r.json() as {queued?:number;skipped?:number;error?:string};if(!r.ok)return notify(j.error||"Start fehlgeschlagen.");setStore(s=>({...s,campaigns:s.campaigns.map(x=>x.id===c.id?{...x,status:"Aktiv"}:x)}));notify(`${j.queued||0} Schritte eingeplant · ${j.skipped||0} gesperrt`)}
 function addMailbox(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const email=String(f.get("email")||"");if(!email.includes("@"))return;setStore(s=>({...s,mailboxes:[...s.mailboxes,{id:String(f.get("id")||uid("mb")),name:String(f.get("name")||"Mailbox"),email,provider:String(f.get("provider")||"Google") as Mailbox["provider"],dailyLimit:5,sentToday:0,warmupDay:1,health:70,enabled:true,spf:false,dkim:false,dmarc:false}]}));e.currentTarget.reset();notify("Mailbox angelegt · 5/Tag Startlimit")}
 async function domainCheck(m:Mailbox){const domain=m.email.split("@")[1];const r=await fetch("/api/domain/health",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({domain})});const j=await r.json() as {spf?:boolean;dmarc?:boolean;score?:number;error?:string};if(!r.ok)return notify(j.error||"Domain Check fehlgeschlagen");setStore(s=>({...s,mailboxes:s.mailboxes.map(x=>x.id===m.id?{...x,spf:Boolean(j.spf),dmarc:Boolean(j.dmarc),health:Math.max(x.health,j.score||0)}:x)}));notify(`${domain}: SPF ${j.spf?"OK":"fehlt"} · DMARC ${j.dmarc?"OK":"fehlt"}`)}
 function ramp(id:string){setStore(s=>({...s,mailboxes:s.mailboxes.map(m=>{if(m.id!==id)return m;const d=m.warmupDay+1;const dailyLimit=d<4?5:d<7?10:d<11?15:d<15?20:d<19?25:30;return{...m,warmupDay:d,dailyLimit}})}))}
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">ER</span><div><strong>EnergyRadar</strong><small>Revenue Engine</small></div></div><nav>{nav.map(n=><button key={n.id} className={`nav-item ${section===n.id?"active":""}`} onClick={()=>setSection(n.id)}><span>{n.icon}</span>{n.label}</button>)}</nav><div className="sidebar-foot"><i className="health-dot"/><span>{saving?"Speichert…":"System online"}</span><small>{health?`${health.configured}/${health.total} Integrationen`:"Health lädt"}</small></div></aside><section className="workspace"><header className="topbar"><div><small>WALKENHORST ENERGY SALES OS</small><h1>{nav.find(n=>n.id===section)?.label}</h1></div><div className="top-actions"><span className="live-pill">● LIVE</span><div className="avatar">AW</div></div></header><div className="content">
 {section==="cockpit"&&<><div className="hero-grid"><div className="hero-card"><div><span className="eyebrow">REVENUE PRIORITY</span><h2>{stats.hot} heiße Chancen für den Vertrieb.</h2><p>EnergyRadar kombiniert Energie-Potenzial, Kontaktaktivität, Kampagnen und Pipeline in einer Oberfläche.</p></div><div className="hero-number">{stats.hot}<small>HOT LEADS</small></div></div><div className="capacity-card"><span>Mailbox Kapazität</span><strong>{stats.capacity}/Tag</strong><div className="progress"><i style={{width:`${Math.min(100,stats.capacity/1.5)}%`}}/></div><small>kontrolliertes Ramp-up · keine künstlichen Warm-up-Interaktionen</small></div></div><div className="metric-grid"><div className="metric"><span>Leads</span><strong>{stats.leads}</strong><small>im Radar</small></div><div className="metric"><span>Pipeline</span><strong>{money(stats.pipeline)}</strong><small>offen</small></div><div className="metric"><span>Termine</span><strong>{stats.appointments}</strong><small>gebucht</small></div><div className="metric"><span>Health</span><strong>{stats.health}%</strong><small>aktive Mailboxes</small></div></div><div className="panel"><div className="panel-head"><div><h3>Hot Lead Queue</h3><p>höchste kombinierte Scores zuerst</p></div></div><div className="lead-list">{hottest.length?hottest.map(l=><div className="lead-row" key={l.id}><div><strong>{l.company}</strong><small>{l.city} · {l.industry}</small></div><span className={scoreClass(l.energyScore)}>E {l.energyScore}</span><span className={scoreClass(l.intentScore)}>I {l.intentScore}</span><select value={l.stage} onChange={e=>stageLead(l.id,e.target.value as Stage)}>{stages.map(x=><option key={x}>{x}</option>)}</select></div>):<div className="callout">Noch keine Leads. Im Lead Radar den ersten Datensatz anlegen.</div>}</div></div></>}
 {section==="leads"&&<div className="two-col wide-left"><div className="panel"><div className="panel-head"><div><h3>Lead Intelligence</h3><p>Verify + Score + Pipeline</p></div></div><div className="table-wrap"><table><thead><tr><th>Unternehmen</th><th>E-Mail</th><th>Energy</th><th>Intent</th><th>Stage</th><th></th></tr></thead><tbody>{store.leads.map(l=><tr key={l.id}><td><strong>{l.company}</strong><small>{l.city} · {l.industry}</small></td><td>{l.email||"—"}</td><td><span className={scoreClass(l.energyScore)}>{l.energyScore}</span></td><td><span className={scoreClass(l.intentScore)}>{l.intentScore}</span></td><td><select value={l.stage} onChange={e=>stageLead(l.id,e.target.value as Stage)}>{stages.map(x=><option key={x}>{x}</option>)}</select></td><td><button className="ghost" onClick={()=>void verify(l.email)}>Verify</button></td></tr>)}</tbody></table></div></div><form className="panel form-panel" onSubmit={addLead}><div className="panel-head"><div><h3>Neuer Lead</h3><p>Energy Score wird automatisch berechnet</p></div></div><label>Unternehmen<input name="company" required/></label><div className="split"><label>Kontakt<input name="contact"/></label><label>Stadt<input name="city"/></label></div><label>E-Mail<input name="email" type="email"/></label><label>Telefon<input name="phone"/></label><label>Website<input name="website"/></label><label>Branche<input name="industry"/></label><div className="split"><label>Mitarbeiter<input name="employees" type="number" min="0"/></label><label>Dachfläche m²<input name="roofArea" type="number" min="0"/></label></div><label>Dealwert €<input name="dealValue" type="number" min="0"/></label><label className="check"><input name="pvExisting" type="checkbox"/> PV vorhanden</label><button className="primary">Analysieren & speichern</button></form></div>}
 {section==="campaigns"&&<div className="panel"><div className="panel-head"><div><h3>Campaign Engine</h3><p>Mailbox-Rotation · Sequenzen · Stop-on-Reply</p></div><button className="ghost" onClick={()=>void aiCampaign()}>✦ KI-Kampagne</button></div>{store.campaigns.map(c=><div className="campaign-card" key={c.id}><div className="campaign-head"><div><span className={c.status==="Aktiv"?"status-green":"status"}>{c.status}</span><h3>{c.name}</h3><p>{c.audience}</p></div><button className="ghost" onClick={()=>void launch(c)}>Starten</button></div><div className="campaign-metrics"><span><small>Limit</small><b>{c.dailyLimit}</b></span><span><small>Sent</small><b>{c.sent}</b></span><span><small>Replies</small><b>{c.replies}</b></span><span><small>Termine</small><b>{c.appointments}</b></span></div><div className="sequence">{c.steps.map((x,i)=><div className="sequence-step" key={`${c.id}-${i}`}><span>{i+1}</span><div><small>TAG +{x.waitDays}</small><strong>{x.subject}</strong><p>{x.body.slice(0,100)}…</p></div></div>)}</div></div>)}</div>}
 {section==="mailboxes"&&<div className="two-col wide-left"><div className="panel"><div className="panel-head"><div><h3>Mailbox Fleet</h3><p>5 → 10 → 15 → 20 → 25 → 30 / Tag</p></div></div><div className="mailboxes">{store.mailboxes.map(m=><div className="mailbox-card" key={m.id}><div className="mailbox-top"><span className="mail-icon">✉</span><div><strong>{m.name}</strong><small>{m.email} · {m.provider}</small></div><button className={`switch ${m.enabled?"on":""}`} onClick={()=>setStore(s=>({...s,mailboxes:s.mailboxes.map(x=>x.id===m.id?{...x,enabled:!x.enabled}:x)}))}><i/></button></div><div className="mail-health"><span>Health <b>{m.health}%</b></span><span>Tag {m.warmupDay} · {m.dailyLimit}/Tag</span></div><div className="progress"><i style={{width:`${m.health}%`}}/></div><div className="dns"><span className={m.spf?"ok":""}>SPF</span><span className={m.dkim?"ok":""}>DKIM</span><span className={m.dmarc?"ok":""}>DMARC</span><button className="link-btn" onClick={()=>void domainCheck(m)}>Prüfen</button><button className="link-btn" onClick={()=>ramp(m.id)}>Ramp-up</button></div></div>)}</div></div><form className="panel form-panel" onSubmit={addMailbox}><div className="panel-head"><div><h3>Mailbox hinzufügen</h3><p>ID = Credential-ID im Server-Secret</p></div></div><label>Credential-ID<input name="id" placeholder="mb-andreas" required/></label><label>Name<input name="name"/></label><label>E-Mail<input name="email" type="email" required/></label><label>Provider<select name="provider"><option>Google</option><option>Microsoft</option><option>SMTP</option></select></label><button className="primary">Hinzufügen</button></form></div>}
 {section==="pipeline"&&<div className="kanban">{stages.map(st=><div className="kanban-col" key={st}><div className="kanban-title"><strong>{st}</strong><span>{store.leads.filter(l=>l.stage===st).length}</span></div>{store.leads.filter(l=>l.stage===st).map(l=><div className="deal-card" key={l.id}><span className={scoreClass(Math.max(l.energyScore,l.intentScore))}>{Math.max(l.energyScore,l.intentScore)}</span><h4>{l.company}</h4><p>{l.contact||l.city}</p><b>{money(l.dealValue)}</b><select value={l.stage} onChange={e=>stageLead(l.id,e.target.value as Stage)}>{stages.map(x=><option key={x}>{x}</option>)}</select></div>)}</div>)}</div>}
 {section==="analytics"&&<><div className="metric-grid"><div className="metric"><span>Leads</span><strong>{stats.leads}</strong></div><div className="metric"><span>Hot</span><strong>{stats.hot}</strong></div><div className="metric"><span>Pipeline</span><strong>{money(stats.pipeline)}</strong></div><div className="metric"><span>Kapazität</span><strong>{stats.capacity}/Tag</strong></div></div><div className="panel"><div className="panel-head"><div><h3>Segment Intelligence</h3><p>Ø Energy Score nach Branche</p></div></div><div className="segment-bars">{Array.from(new Set(store.leads.map(l=>l.industry||"Sonstige"))).map(ind=>{const a=store.leads.filter(l=>(l.industry||"Sonstige")===ind);const avg=a.length?Math.round(a.reduce((x,y)=>x+y.energyScore,0)/a.length):0;return <div key={ind}><span>{ind}</span><div className="bar"><i style={{width:`${avg}%`}}/></div><b>{avg}</b></div>})}</div></div></>}
 {section==="integrations"&&<div className="two-col"><div className="panel"><div className="panel-head"><div><h3>System Readiness</h3><p>Live aus den Server-Variablen</p></div></div><div className="integration-list">{health?Object.entries(health.checks).map(([k,v])=><div key={k}><span className={`integration-icon ${v?"ok-bg":""}`}>{v?"✓":"!"}</span><div><strong>{k}</strong><small>{v?"bereit":"Credential fehlt"}</small></div></div>):<div className="callout">Health API lädt…</div>}</div></div><div className="panel"><div className="panel-head"><div><h3>Credentials</h3><p>Secrets niemals im Browser speichern</p></div></div><div className="callout">DATABASE_URL<br/>OPENAI_API_KEY<br/>NEXT_PUBLIC_APP_URL<br/>CRON_SECRET<br/>WEBHOOK_SECRET<br/>MAILBOX_CREDENTIALS_JSON<br/>GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET (optional OAuth)<br/>MICROSOFT_CLIENT_ID / MICROSOFT_CLIENT_SECRET (optional OAuth)<br/>GOOGLE_MAPS_API_KEY oder MAPBOX_TOKEN<br/><br/>MAILBOX_CREDENTIALS_JSON enthält pro Postfach ID, provider, email und serverseitige Token bzw. SMTP-Zugangsdaten.</div></div></div>}
 </div></section>{toast&&<div className="toast">{toast}</div>}</main>
}
