"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Stage="Neu"|"Kontaktiert"|"Engaged"|"Termin"|"Angebot"|"Gewonnen"|"Verloren";
type Lead={id:string;company:string;contact:string;email:string;phone:string;website:string;city:string;industry:string;employees:number;roofArea:number;pvExisting:boolean;energyScore:number;intentScore:number;stage:Stage;dealValue:number;notes:string};
type Step={waitDays:number;subject:string;body:string};
type Campaign={id:string;name:string;audience:string;status:"Entwurf"|"Aktiv"|"Pausiert";dailyLimit:number;steps:Step[];sent:number;replies:number;positive:number;appointments:number};
type Mailbox={id:string;name:string;email:string;provider:"Google"|"Microsoft"|"SMTP";dailyLimit:number;sentToday:number;warmupDay:number;health:number;enabled:boolean;spf:boolean;dkim:boolean;dmarc:boolean};
type Store={leads:Lead[];campaigns:Campaign[];mailboxes:Mailbox[];settings:{companyName:string;senderName:string;calendarUrl:string;timezone:string}};
type Health={checks:Record<string,boolean>;configured:number;total:number;ready:boolean};

const stages:Stage[]=["Neu","Kontaktiert","Engaged","Termin","Angebot","Gewonnen","Verloren"];
const fallback:Store={
 settings:{companyName:"Walkenhorst Energie",senderName:"Andreas Walkenhorst",calendarUrl:"",timezone:"Europe/Berlin"},
 leads:[
  {id:"demo-1",company:"Müller Metalltechnik GmbH",contact:"Thomas Müller",email:"t.mueller@example.com",phone:"+49 711 555 204",website:"mueller-metall.de",city:"Stuttgart",industry:"Metallverarbeitung",employees:86,roofArea:3200,pvExisting:false,energyScore:92,intentScore:88,stage:"Engaged",dealValue:42000,notes:"Produktionshalle, hoher Eigenverbrauch plausibel."},
  {id:"demo-2",company:"SüdLogistik GmbH",contact:"Nina Weber",email:"n.weber@example.com",phone:"+49 731 889 120",website:"suedlogistik.de",city:"Ulm",industry:"Logistik",employees:145,roofArea:6100,pvExisting:false,energyScore:96,intentScore:71,stage:"Kontaktiert",dealValue:68000,notes:"Große Dachfläche + Fuhrpark."}
 ],
 campaigns:[{id:"demo-c",name:"Gewerbedächer BW",audience:"Produktion & Logistik, 20–250 MA, Baden-Württemberg",status:"Entwurf",dailyLimit:150,sent:0,replies:0,positive:0,appointments:0,steps:[{waitDays:0,subject:"Kurze Frage zu {{company}}",body:"Hallo {{first_name}},\n\nich habe mir den Standort von {{company}} kurz angesehen. Ich habe eine unverbindliche Voranalyse vorbereitet: {{analysis_link}}\n\nViele Grüße\n{{sender_name}}"},{waitDays:3,subject:"Re: Kurze Frage zu {{company}}",body:"Hallo {{first_name}}, kurze Nachfrage: Ist das Thema für Sie grundsätzlich relevant?"},{waitDays:7,subject:"Re: {{company}}",body:"Falls es aktuell keine Priorität hat, reicht ein kurzes 'später'."}]}],
 mailboxes:[]
};

function uid(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function money(v:number){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(v)}
function score(v:number){return v>=85?"score score-hot":v>=65?"score score-warm":"score"}

export default function EnergyRadarPro(){
 const [section,setSection]=useState("cockpit"); const [store,setStore]=useState<Store>(fallback); const [toast,setToast]=useState(""); const [health,setHealth]=useState<Health|null>(null); const [saving,setSaving]=useState(false);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2600)};
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/state");if(r.ok){const j=await r.json();if(j.state)setStore(j.state)}}catch{}try{const h=await fetch("/api/system/health");if(h.ok)setHealth(await h.json())}catch{}})()},[]);
 useEffect(()=>{const t=setTimeout(async()=>{try{setSaving(true);await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(store)})}catch{}finally{setSaving(false)}},700);return()=>clearTimeout(t)},[store]);
 const stats=useMemo(()=>({leads:store.leads.length,hot:store.leads.filter(x=>x.energyScore>=80||x.intentScore>=80).length,appointments:store.leads.filter(x=>x.stage==="Termin").length,pipeline:store.leads.filter(x=>!["Gewonnen","Verloren"].includes(x.stage)).reduce((a,b)=>a+b.dealValue,0),capacity:store.mailboxes.filter(x=>x.enabled).reduce((a,b)=>a+b.dailyLimit,0),health:store.mailboxes.length?Math.round(store.mailboxes.reduce((a,b)=>a+b.health,0)/store.mailboxes.length):0}),[store]);
 const hot=useMemo(()=>[...store.leads].sort((a,b)=>(b.energyScore+b.intentScore)-(a.energyScore+a.intentScore)).slice(0,8),[store.leads]);
 async function addLead(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const raw={industry:String(f.get("industry")||""),employees:Number(f.get("employees")||0),roofArea:Number(f.get("roofArea")||0),pvExisting:f.get("pvExisting")==="on"};let energyScore=50;try{const r=await fetch("/api/energy/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(raw)});if(r.ok)energyScore=(await r.json()).score}catch{}const lead:Lead={id:uid("lead"),company:String(f.get("company")||""),contact:String(f.get("contact")||""),email:String(f.get("email")||""),phone:String(f.get("phone")||""),website:String(f.get("website")||""),city:String(f.get("city")||""),industry:raw.industry,employees:raw.employees,roofArea:raw.roofArea,pvExisting:raw.pvExisting,energyScore,intentScore:0,stage:"Neu",dealValue:Number(f.get("dealValue")||0),notes:""};if(!lead.company)return;setStore(s=>({...s,leads:[lead,...s.leads]}));e.currentTarget.reset();notify(`Lead angelegt · Energy Score ${energyScore}`)}
 async function verifyLead(lead:Lead){if(!lead.email)return notify("Keine E-Mail vorhanden.");const r=await fetch("/api/email/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:lead.email})});const j=await r.json();notify(r.ok?`E-Mail: ${j.status} · MX ${j.checks.mx?"OK":"fehlt"}`:j.error)}
 async function checkDomain(m:Mailbox){const d=m.email.split("@")[1];const r=await fetch("/api/domain/health",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({domain:d})});const j=await r.json();if(r.ok){setStore(s=>({...s,mailboxes:s.mailboxes.map(x=>x.id===m.id?{...x,spf:j.spf,dmarc:j.dmarc,health:Math.max(x.health,j.score)}:x)}));notify(`${d}: SPF ${j.spf?"✓":"✕"} · DMARC ${j.dmarc?"✓":"✕"}`)}else notify(j.error)}
 async function aiCampaign(){const audience=prompt("Zielgruppe für die Kampagne?");if(!audience)return;const offer=prompt("Angebot / Nutzen?")||"Energie-Potenzialanalyse für Gewerbestandorte";notify("KI erstellt Kampagne …");const r=await fetch("/api/ai/campaign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({audience,offer,sender:store.settings.senderName})});const j=await r.json();if(!r.ok)return notify(j.error||"KI nicht verbunden.");const c:Campaign={id:uid("campaign"),name:j.name,audience:j.audience,status:"Entwurf",dailyLimit:150,steps:j.steps,sent:0,replies:0,positive:0,appointments:0};setStore(s=>({...s,campaigns:[c,...s.campaigns]}));notify("KI-Kampagne erstellt.")}
 async function launch(c:Campaign){const eligible=store.leads.filter(l=>l.email&&!["Gewonnen","Verloren"].includes(l.stage));if(!eligible.length)return notify("Keine versandfähigen Leads.");const r=await fetch("/api/campaigns/launch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({campaign:c,leads:eligible,mailboxes:store.mailboxes,senderName:store.settings.senderName})});const j=await r.json();if(!r.ok)return notify(j.error||"Start fehlgeschlagen.");setStore(s=>({...s,campaigns:s.campaigns.map(x=>x.id===c.id?{...x,status:"Aktiv"}:x)}));notify(`${j.queued} E-Mails eingeplant · ${j.skipped} unterdrückt`)}
 function addMailbox(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const email=String(f.get("email")||"");if(!email.includes("@"))return;const m:Mailbox={id:String(f.get("id")||uid("mb")),name:String(f.get("name")||"Mailbox"),email,provider:String(f.get("provider")||"Google") as Mailbox["provider"],dailyLimit:5,sentToday:0,warmupDay:1,health:70,enabled:true,spf:false,dkim:false,dmarc:false};setStore(s=>({...s,mailboxes:[...s.mailboxes,m]}));e.currentTarget.reset();notify("Mailbox angelegt · Startlimit 5/Tag")}
 function ramp(id:string){setStore(s=>({...s,mailboxes:s.mailboxes.map(m=>{if(m.id!==id)return m;const d=m.warmupDay+1;const lim=d<4?5:d<7?10:d<11?15:d<15?20:d<19?25:30;return{...m,warmupDay:d,dailyLimit:lim}})}))}
 const nav=[...["cockpit","◉","Cockpit"],["leads","⌁","Lead Radar"],["campaigns","✦","Kampagnen"],["mailboxes","✉","Mailboxes"],["pipeline","▦","Pipeline"],["analytics","↗","Analytics"],["integrations","⚙","Integrationen"]] as string[][];
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">ER</span><div><strong>EnergyRadar</strong><small>Revenue Engine</small></div></div><nav>{nav.map(n=><button key={n[0]} className={`nav-item ${section===n[0]?"active":""}`} onClick={()=>setSection(n[0])}><span>{n[1]}</span>{n[2]}</button>)}</nav><div className="sidebar-foot"><i className="health-dot"/><span>{saving?"Speichert…":"System online"}</span><small>{health?`${health.configured}/${health.total} Integrationen`:"Health lädt…"}</small></div></aside><section className="workspace"><header className="topbar"><div><small>WALKENHORST ENERGY SALES OS</small><h1>{nav.find(n=>n[0]===section)?.[2]}</h1></div><div className="top-actions"><span className="live-pill">● LIVE</span><div className="avatar">AW</div></div></header><div className="content">
 {section==="cockpit"&&<><div className="hero-grid"><div className="hero-card"><div><span className="eyebrow">TODAY'S PRIORITY</span><h2>{stats.hot} heiße Energie-Chancen warten auf den nächsten Schritt.</h2><p>Energy Score + Intent Score priorisieren Unternehmen mit hoher Relevanz und Interaktion.</p></div><div className="hero-number">{stats.hot}<small>HOT LEADS</small></div></div><div className="capacity-card"><span>Versandkapazität</span><strong>{stats.capacity}/Tag</strong><div className="progress"><i style={{width:`${Math.min(100,stats.capacity/1.5)}%`}}/></div><small>{store.mailboxes.filter(x=>x.enabled).length} aktive Mailboxes · Ramp-up statt künstlichem Warm-up</small></div></div><div className="metric-grid"><div className="metric"><span>Leads</span><strong>{stats.leads}</strong><small>im Radar</small></div><div className="metric"><span>Pipeline</span><strong>{money(stats.pipeline)}</strong><small>offenes Potenzial</small></div><div className="metric"><span>Termine</span><strong>{stats.appointments}</strong><small>aktuell</small></div><div className="metric"><span>Mailbox Health</span><strong>{stats.health}%</strong><small>Ø Senderstatus</small></div></div><div className="two-col wide-left"><div className="panel"><div className="panel-head"><div><h3>Hot Lead Queue</h3><p>Jetzt zuerst anrufen</p></div></div><div className="lead-list">{hot.map(l=><div className="lead-row" key={l.id}><div><strong>{l.company}</strong><small>{l.city} · {l.industry}</small></div><span className={score(l.energyScore)}>E {l.energyScore}</span><span className={score(l.intentScore)}>I {l.intentScore}</span><select value={l.stage} onChange={e=>setStore(s=>({...s,leads:s.leads.map(x=>x.id===l.id?{...x,stage:e.target.value as Stage}:x)}))}>{stages.map(x=><option key={x}>{x}</option>)}</select></div>)}</div></div><div className="panel"><div className="panel-head"><div><h3>System Readiness</h3><p>Credentials & Infrastruktur</p></div></div><div className="integration-list">{health&&Object.entries(health.checks).map(([k,v])=><div key={k}><span className={`integration-icon ${v?"ok-bg":""}`}>{v?"✓":"!"}</span><div><strong>{k}</strong><small>{v?"verbunden":"noch konfigurieren"}</small></div></div>)}</div></div></div></>}
 {section==="leads"&&<div className="two-col wide-left"><div className="panel"><div className="panel-head"><div><h3>Lead Intelligence</h3><p>Energy- und Intent-Scores</p></div></div><div className="table-wrap"><table><thead><tr><th>Unternehmen</th><th>E-Mail</th><th>Energy</th><th>Intent</th><th>Pipeline</th><th>Check</th></tr></thead><tbody>{store.leads.map(l=><tr key={l.id}><td><strong>{l.company}</strong><small>{l.city} · {l.industry}</small></td><td>{l.email||"—"}</td><td><span className={score(l.energyScore)}>{l.energyScore}</span></td><td><span className={score(l.intentScore)}>{l.intentScore}</span></td><td><select value={l.stage} onChange={e=>setStore(s=>({...s,leads:s.leads.map(x=>x.id===l.id?{...x,stage:e.target.value as Stage}:x)}))}>{stages.map(x=><option key={x}>{x}</option>)}</select></td><td><button className="ghost" onClick={()=>verifyLead(l)}>Verify</button></td></tr>)}</tbody></table></div></div><form className="panel form-panel" onSubmit={addLead}><div className="panel-head"><div><h3>Lead hinzufügen</h3><p>Score wird serverseitig berechnet</p></div></div><label>Unternehmen<input name="company" required/></label><div className="split"><label>Kontakt<input name="contact"/></label><label>Stadt<input name="city"/></label></div><label>E-Mail<input name="email" type="email"/></label><label>Telefon<input name="phone"/></label><label>Website<input name="website"/></label><label>Branche<input name="industry" placeholder="z. B. Metallverarbeitung"/></label><div className="split"><label>Mitarbeiter<input name="employees" type="number" min="0"/></label><label>Dachfläche m²<input name="roofArea" type="number" min="0"/></label></div><label>Dealwert €<input name="dealValue" type="number" min="0"/></label><label className="check"><input name="pvExisting" type="checkbox"/> PV bereits vorhanden</label><button className="primary">Analysieren & anlegen</button></form></div>}
 {section==="campaigns"&&<><div className="panel"><div className="panel-head"><div><h3>Campaign Engine</h3><p>Sequenzen, Rotation, Stop-on-Reply, Suppression</p></div><button className="ghost" onClick={aiCampaign}>✦ KI-Kampagne erstellen</button></div>{store.campaigns.map(c=><div className="campaign-card" key={c.id}><div className="campaign-head"><div><span className={c.status==="Aktiv"?"status-green":"status"}>{c.status}</span><h3>{c.name}</h3><p>{c.audience}</p></div><button className="ghost" onClick={()=>launch(c)}>Kampagne starten</button></div><div className="campaign-metrics"><span><small>Limit</small><b>{c.dailyLimit}/Tag</b></span><span><small>Gesendet</small><b>{c.sent}</b></span><span><small>Replies</small><b>{c.replies}</b></span><span><small>Termine</small><b>{c.appointments}</b></span></div><div className="sequence">{c.steps.map((s,i)=><div className="sequence-step" key={i}><span>{i+1}</span><div><small>TAG +{s.waitDays}</small><strong>{s.subject}</strong><p>{s.body.slice(0,120)}…</p></div></div>)}</div></div>)}</div></>}
 {section==="mailboxes"&&<div className="two-col wide-left"><div className="panel"><div className="panel-head"><div><h3>Mailbox Fleet</h3><p>Kontrolliertes Ramp-up · max. 30/Tag als Default</p></div></div><div className="mailboxes">{store.mailboxes.map(m=><div className="mailbox-card" key={m.id}><div className="mailbox-top"><span className="mail-icon">✉</span><div><strong>{m.name}</strong><small>{m.email} · {m.provider}</small></div><button className={`switch ${m.enabled?"on":""}`} onClick={()=>setStore(s=>({...s,mailboxes:s.mailboxes.map(x=>x.id===m.id?{...x,enabled:!x.enabled}:x)}))}><i/></button></div><div className="mail-health"><span>Health <b>{m.health}%</b></span><span>Tag {m.warmupDay} · {m.dailyLimit}/Tag</span></div><div className="progress"><i style={{width:`${m.health}%`}}/></div><div className="dns"><span className={m.spf?"ok":""}>SPF</span><span className={m.dkim?"ok":""}>DKIM</span><span className={m.dmarc?"ok":""}>DMARC</span><button className="link-btn" onClick={()=>checkDomain(m)}>Domain prüfen</button><button className="link-btn" onClick={()=>ramp(m.id)}>+ Ramp-up Tag</button></div></div>)}</div></div><form className="panel form-panel" onSubmit={addMailbox}><div className="panel-head"><div><h3>Mailbox hinzufügen</h3><p>ID muss zur Credential-ID passen</p></div></div><label>Credential-ID<input name="id" placeholder="mb-andreas" required/></label><label>Name<input name="name" placeholder="Andreas"/></label><label>E-Mail<input name="email" type="email" required/></label><label>Provider<select name="provider"><option>Google</option><option>Microsoft</option><option>SMTP</option></select></label><button className="primary">Mailbox anlegen</button><div className="callout">Die geheimen Tokens/SMTP-Passwörter bleiben ausschließlich serverseitig in <b>MAILBOX_CREDENTIALS_JSON</b>. Die ID hier verknüpft das Postfach mit dem passenden Credential.</div></form></div>}
 {section==="pipeline"&&<div className="kanban">{stages.map(st=><div className="kanban-col" key={st}><div className="kanban-title"><strong>{st}</strong><span>{store.leads.filter(l=>l.stage===st).length}</span></div>{store.leads.filter(l=>l.stage===st).map(l=><div className="deal-card" key={l.id}><span className={score(Math.max(l.energyScore,l.intentScore))}>{Math.max(l.energyScore,l.intentScore)}</span><h4>{l.company}</h4><p>{l.contact||l.city}</p><b>{money(l.dealValue)}</b><select value={l.stage} onChange={e=>setStore(s=>({...s,leads:s.leads.map(x=>x.id===l.id?{...x,stage:e.target.value as Stage}:x)}))}>{stages.map(x=><option key={x}>{x}</option>)}</select></div>)}</div>)}</div>}
 {section==="analytics"&&<><div className="metric-grid"><div className="metric"><span>Leads</span><strong>{stats.leads}</strong></div><div className="metric"><span>Hot</span><strong>{stats.hot}</strong></div><div className="metric"><span>Pipeline</span><strong>{money(stats.pipeline)}</strong></div><div className="metric"><span>Versand</span><strong>{stats.capacity}/Tag</strong></div></div><div className="panel"><div className="panel-head"><div><h3>Segment Intelligence</h3><p>Ø Energy Score nach Branche</p></div></div><div className="segment-bars">{Array.from(new Set(store.leads.map(l=>l.industry))).map(ind=>{const ls=store.leads.filter(l=>l.industry===ind);const avg=Math.round(ls.reduce((a,b)=>a+b.energyScore,0)/ls.length);return <div key={ind}><span>{ind||"Sonstige"}</span><div className="bar"><i style={{width:`${avg}%`}}/></div><b>{avg}</b></div>})}</div></div></>}
 {section==="integrations"&&<div className="two-col"><div className="panel"><div className="panel-head"><div><h3>Integrationen</h3><p>Serverseitige Secrets</p></div></div><div className="integration-list">{health?Object.entries(health.checks).map(([k,v])=><div key={k}><span className={`integration-icon ${v?"ok-bg":""}`}>{v?"✓":"!"}</span><div><strong>{k}</strong><small>{v?"bereit":"Credential fehlt"}</small></div></div>):"Lädt…"}</div></div><div className="panel"><div className="panel-head"><div><h3>Benötigte Environment Variablen</h3><p>Danach schalten die Module automatisch auf bereit</p></div></div><div className="callout">DATABASE_URL<br/>OPENAI_API_KEY<br/>OPENAI_MODEL (optional)<br/>NEXT_PUBLIC_APP_URL<br/>CRON_SECRET<br/>WEBHOOK_SECRET<br/>MAILBOX_CREDENTIALS_JSON<br/>GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET (OAuth optional)<br/>MICROSOFT_CLIENT_ID / MICROSOFT_CLIENT_SECRET (OAuth optional)<br/>GOOGLE_MAPS_API_KEY oder MAPBOX_TOKEN<br/>EMAIL_VERIFIER_API_KEY (optional)</div></div></div>}
 </div></section>{toast&&<div className="toast">{toast}</div>}</main>
}
