"use client";
import { useState } from "react";

type Item={id:number;leadId:string;company:string;contact:string;from:string;subject:string;mailboxId:string;createdAt:string;stage:string};
export default function InboxWidget(){
 const [open,setOpen]=useState(false);const [items,setItems]=useState<Item[]>([]);const [error,setError]=useState("");
 async function load(){try{const r=await fetch("/api/inbox");const j=await r.json() as {items?:Item[];error?:string};if(!r.ok)throw new Error(j.error||"Inbox Fehler");setItems(j.items||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Inbox Fehler")}}
 return <><button onClick={()=>{setOpen(true);void load()}} style={{position:"fixed",right:270,bottom:24,zIndex:80,border:"1px solid #51402b",background:"#211a11",color:"#f0c97c",padding:"12px 15px",borderRadius:13,fontWeight:850,cursor:"pointer",boxShadow:"0 18px 45px rgba(0,0,0,.35)"}}>✉ Inbox</button>{open&&<div onClick={()=>setOpen(false)} style={{position:"fixed",inset:0,zIndex:100,background:"rgba(3,6,10,.78)",backdropFilter:"blur(8px)",display:"grid",placeItems:"center",padding:20}}><div onClick={e=>e.stopPropagation()} style={{width:"min(860px,100%)",maxHeight:"88vh",overflow:"auto",background:"#0b121b",border:"1px solid #263547",borderRadius:22,padding:24,color:"#eef4ff",fontFamily:"Inter,system-ui"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start"}}><div><div style={{fontSize:10,color:"#f0c97c",fontWeight:850,letterSpacing:".15em"}}>UNIFIED REPLY INBOX</div><h2 style={{margin:"7px 0",fontSize:28}}>Antworten aus allen Mailboxen</h2><p style={{margin:0,color:"#8290a5",fontSize:13}}>Replies stoppen Sequenzen automatisch und erhöhen den Intent Score.</p></div><button onClick={()=>setOpen(false)} style={{border:0,background:"#182230",color:"#fff",width:36,height:36,borderRadius:10,cursor:"pointer"}}>×</button></div><button onClick={()=>void load()} style={{margin:"18px 0",border:"1px solid #304258",borderRadius:10,padding:"9px 12px",background:"#121c28",color:"#fff",fontWeight:800,cursor:"pointer"}}>Aktualisieren</button>{error&&<div style={{color:"#ff9ba2",fontSize:12}}>{error}</div>}<div style={{display:"grid",gap:9}}>{items.length?items.map(i=><div key={i.id} style={{border:"1px solid #1f2b39",borderRadius:13,padding:14,display:"grid",gridTemplateColumns:"1fr auto",gap:12}}><div><strong style={{fontSize:13}}>{i.company}</strong><small style={{display:"block",marginTop:5,color:"#748297"}}>{i.from} · {i.subject||"(ohne Betreff)"}</small></div><div style={{textAlign:"right"}}><span style={{fontSize:10,color:"#66e9aa"}}>{i.stage}</span><small style={{display:"block",marginTop:5,color:"#657286"}}>{new Date(i.createdAt).toLocaleString("de-DE")}</small></div></div>):<div style={{padding:20,border:"1px solid #1f2b39",borderRadius:13,color:"#748297"}}>Noch keine Antworten synchronisiert.</div>}</div></div></div>}</>
}
