"use client";
import { FormEvent, useState } from "react";

type FoundLead={id:string;company:string;contact:string;email:string;phone:string;website:string;city:string;industry:string;employees:number;roofArea:number;pvExisting:boolean;energyScore:number;intentScore:number;stage:string;dealValue:number;notes:string;lat?:number;lng?:number};
type Solar={roofAreaMeters2?:number|null;estimatedKwp?:number|null;pvDetected?:boolean;maxYearlyEnergyKwh?:number|null;imageryQuality?:string|null;error?:string};
type Store={leads?:Array<Record<string,unknown>>;campaigns?:unknown[];mailboxes?:unknown[];settings?:Record<string,unknown>};

export default function LeadFinderWidget(){
 const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const [results,setResults]=useState<FoundLead[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function search(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/leads/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query,pageSize:20})});const j=await r.json() as {leads?:FoundLead[];error?:string};if(!r.ok)throw new Error(j.error||"Suche fehlgeschlagen");setResults(j.leads||[]);setMessage(`${j.leads?.length||0} Unternehmen gefunden.`)}catch(e){setMessage(e instanceof Error?e.message:"Suche fehlgeschlagen")}finally{setBusy(false)}}
 async function importLead(found:FoundLead){setBusy(true);setMessage(`Analysiere ${found.company} …`);try{let solar:Solar={};if(typeof found.lat==="number"&&typeof found.lng==="number"){const sr=await fetch("/api/solar/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({lat:found.lat,lng:found.lng})});if(sr.ok)solar=await sr.json() as Solar}const er=await fetch("/api/energy/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({industry:found.industry,employees:found.employees||0,roofArea:solar.roofAreaMeters2||0,pvExisting:Boolean(solar.pvDetected)})});const energy=er.ok?await er.json() as {score?:number}:{score:35};const stateResponse=await fetch("/api/state");const stateJson=await stateResponse.json() as {state?:Store};const state:Store=stateJson.state||{};const current=state.leads||[];if(current.some(l=>String(l.company).toLowerCase()===found.company.toLowerCase()))throw new Error("Unternehmen ist bereits im Radar.");const lead={...found,roofArea:Number(solar.roofAreaMeters2||0),pvExisting:Boolean(solar.pvDetected),energyScore:Number(energy.score||35),intentScore:0,stage:"Neu",dealValue:0,notes:[found.notes,solar.estimatedKwp?`Solar API: ca. ${solar.estimatedKwp} kWp Maximalpotenzial`:"",solar.maxYearlyEnergyKwh?`Max. Modell-Erzeugung ca. ${solar.maxYearlyEnergyKwh.toLocaleString("de-DE")} kWh/Jahr`:"",solar.imageryQuality?`Imagery: ${solar.imageryQuality}`:""].filter(Boolean).join(" · ")};const save=await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...state,leads:[lead,...current]})});if(!save.ok)throw new Error("Lead konnte nicht gespeichert werden.");setMessage(`${found.company} importiert · Energy Score ${lead.energyScore}`);setResults(r=>r.filter(x=>x.id!==found.id));window.setTimeout(()=>location.reload(),700)}catch(e){setMessage(e instanceof Error?e.message:"Import fehlgeschlagen")}finally{setBusy(false)}}
 return <><button onClick={()=>setOpen(true)} style={{position:"fixed",right:145,bottom:24,zIndex:80,border:"1px solid #28465d",background:"#101b27",color:"#9dcfff",padding:"12px 15px",borderRadius:13,fontWeight:850,cursor:"pointer",boxShadow:"0 18px 45px rgba(0,0,0,.35)"}}>⌁ Lead Finder</button>{open&&<div onClick={()=>setOpen(false)} style={{position:"fixed",inset:0,zIndex:100,background:"rgba(3,6,10,.78)",backdropFilter:"blur(8px)",display:"grid",placeItems:"center",padding:20}}><div onClick={e=>e.stopPropagation()} style={{width:"min(950px,100%)",maxHeight:"88vh",overflow:"auto",background:"#0b121b",border:"1px solid #263547",borderRadius:22,padding:24,color:"#eef4ff",fontFamily:"Inter,system-ui"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:16}}><div><div style={{fontSize:10,color:"#69aeea",fontWeight:850,letterSpacing:".15em"}}>LEAD INTELLIGENCE</div><h2 style={{margin:"7px 0",fontSize:28}}>Unternehmen finden → Solar prüfen → importieren</h2></div><button onClick={()=>setOpen(false)} style={{border:0,background:"#182230",color:"#fff",width:36,height:36,borderRadius:10,cursor:"pointer"}}>×</button></div><form onSubmit={search} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:10,margin:"20px 0"}}><input value={query} onChange={e=>setQuery(e.target.value)} required placeholder="z. B. Metallverarbeitung Stuttgart" style={{border:"1px solid #29394b",background:"#080e15",color:"#fff",borderRadius:11,padding:"13px 14px"}}/><button disabled={busy} style={{border:0,borderRadius:11,padding:"0 18px",background:"#5de9a7",color:"#062117",fontWeight:900,cursor:"pointer"}}>{busy?"Lädt…":"Suchen"}</button></form>{message&&<div style={{marginBottom:13,color:"#91a0b4",fontSize:12}}>{message}</div>}<div style={{display:"grid",gap:9}}>{results.map(r=><div key={r.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:14,alignItems:"center",border:"1px solid #1e2b3a",borderRadius:13,padding:14}}><div><strong style={{display:"block",fontSize:13}}>{r.company}</strong><small style={{display:"block",marginTop:5,color:"#748297"}}>{r.city} · {r.industry} {r.website?`· ${r.website}`:""}</small></div><button disabled={busy} onClick={()=>void importLead(r)} style={{border:"1px solid #2a6d50",borderRadius:10,padding:"9px 12px",background:"#10251c",color:"#64eaaa",fontWeight:850,cursor:"pointer"}}>Solar prüfen + Import</button></div>)}</div></div></div>}</>
}
