"use client";
import {useCallback,useEffect,useState} from "react";
type P={id:string;policy_key:string;version:number;status:string;description:string;max_weight_shift_per_cycle:number;min_control_weight:number;min_arm_exposure:number;cooldown_hours:number;approved_by:string|null};
type Q={id:string;proposal_type:string;status:string;experiment_id:string|null;payload:Record<string,unknown>;rationale:string;blocker_reasons:string[];created_at:string};
type D={policyVersion:string;autonomyLevel:number;l4Executable:boolean;l5Executable:boolean;currentProductionTarget:string;policies:P[];proposals:Q[];summary:{proposed:number;approved:number;executed:number;blocked:number;activePolicies:number}};
export default function OptimizationControlTower(){
 const[d,setD]=useState<D|null>(null),[busy,setBusy]=useState(""),[err,setErr]=useState(""),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch("/api/outbound/v3/optimization",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error||"Load failed");setD(j)}catch(e){setErr(e instanceof Error?e.message:"Load failed")}},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
 async function post(p:Record<string,unknown>,key:string){setBusy(key);setErr("");setMsg("");try{const r=await fetch("/api/outbound/v3/optimization",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(p)});const j=await r.json();if(!r.ok)throw new Error(j?.error||"Action failed");setMsg("Optimization aktualisiert.");await load()}catch(e){setErr(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}}
 async function policy(p:P,a:"approve"|"activate"|"pause"|"retire"){const reason=window.prompt("Grund:",a==="approve"?"Policy geprüft":"Manuell bestätigt");if(reason)await post({action:"policy",policyId:p.id,policyAction:a,reason},"p"+p.id)}
 async function proposal(q:Q,a:"approve"|"reject"|"execute"){const reason=window.prompt("Grund:",a==="approve"?"Proposal geprüft":"Manuell geprüft");if(reason)await post({action:"proposal",proposalId:q.id,proposalAction:a,reason},"q"+q.id)}
 return <section style={{maxWidth:1540,margin:"0 auto 18px",padding:"0 28px"}}><div style={{border:"1px solid rgba(181,123,255,.2)",background:"rgba(12,8,18,.94)",borderRadius:24,padding:20}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><div style={{fontSize:10,fontWeight:900,letterSpacing:".12em",color:"#c39bff"}}>M10 · OPTIMIZATION AUTOPILOT</div><h2 style={{fontSize:24,margin:"7px 0 6px"}}>Policy-gated Traffic & Experiment Proposals</h2><p style={{fontSize:12,color:"#958b9c",margin:0,maxWidth:900}}>L2 erzeugt nur Vorschläge. Traffic darf erst mit aktiver, menschlich freigegebener Policy und L4 verändert werden; neue Experimente bleiben bis L5 Draft/Approval.</p></div><div style={{display:"flex",gap:6}}><span style={pill}>Level: L{d?.autonomyLevel??2}</span><span style={pill}>L4: {d?.l4Executable?"EXEC":"LOCKED"}</span><span style={pill}>L5: {d?.l5Executable?"EXEC":"LOCKED"}</span></div></div>
  {err&&<div style={{fontSize:10,color:"#ffb3b3",marginTop:10}}>{err}</div>}{msg&&<div style={{fontSize:10,color:"#8be9b2",marginTop:10}}>{msg}</div>}
  <div style={stats}><Stat t="Proposed" v={d?.summary.proposed||0}/><Stat t="Approved" v={d?.summary.approved||0}/><Stat t="Executed" v={d?.summary.executed||0}/><Stat t="Policies Active" v={d?.summary.activePolicies||0}/></div>
  <button disabled={!!busy} style={{...btn(true),marginTop:14}} onClick={()=>void post({action:"cycle"},"cycle")}>Optimization Cycle starten</button>
  <div style={box}><div style={title}>POLICIES</div>{(d?.policies||[]).map(p=><div key={p.id} style={row}><div><b>{p.policy_key} v{p.version}</b><div style={sub}>{p.description} · max shift {Math.round(Number(p.max_weight_shift_per_cycle)*100)}pp · control ≥ {Math.round(Number(p.min_control_weight)*100)}% · min n {p.min_arm_exposure}</div></div><div style={{display:"flex",gap:6,alignItems:"center"}}><span style={sub}>{p.status.toUpperCase()}</span>{p.status==="draft"&&<button disabled={!!busy} style={btn(true)} onClick={()=>void policy(p,"approve")}>Policy freigeben</button>}{["approved","paused"].includes(p.status)&&<button disabled={!!busy} style={btn(true)} onClick={()=>void policy(p,"activate")}>Aktivieren</button>}{p.status==="active"&&<button disabled={!!busy} style={btn(false)} onClick={()=>void policy(p,"pause")}>Pausieren</button>}</div></div>)}</div>
  <div style={box}><div style={title}>OPTIMIZATION PROPOSALS</div>{(d?.proposals||[]).length?(d?.proposals||[]).map(q=><div key={q.id} style={row}><div style={{flex:1}}><b>{q.proposal_type}</b><div style={sub}>{q.rationale}</div><div style={{fontSize:8,color:"#9a86b7",marginTop:4}}>{JSON.stringify(q.payload).slice(0,340)}</div></div><div style={{display:"flex",gap:6,alignItems:"center"}}><span style={sub}>{q.status.toUpperCase()}</span>{q.status==="proposed"&&<><button disabled={!!busy} style={btn(true)} onClick={()=>void proposal(q,"approve")}>Freigeben</button><button disabled={!!busy} style={btn(false)} onClick={()=>void proposal(q,"reject")}>Ablehnen</button></>}{q.status==="approved"&&<button disabled={!!busy||!d?.l4Executable} style={btn(true)} onClick={()=>void proposal(q,"execute")}>Ausführen</button>}</div></div>):<div style={sub}>Noch keine Proposals.</div>}</div>
 </div></section>
}
const pill:React.CSSProperties={fontSize:9,padding:"7px 9px",border:"1px solid rgba(255,255,255,.08)",borderRadius:999,color:"#b9a9c5"};
const stats:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:10,marginTop:18};
const row:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:12,padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.05)",fontSize:10};
const sub:React.CSSProperties={fontSize:9,color:"#897c91",lineHeight:1.45,marginTop:3};
const box:React.CSSProperties={marginTop:12,border:"1px solid rgba(255,255,255,.07)",borderRadius:14,padding:12};
const title:React.CSSProperties={fontSize:9,fontWeight:900,color:"#8d7d98",marginBottom:6};
function Stat({t,v}:{t:string;v:number}){return <div style={{padding:12,border:"1px solid rgba(255,255,255,.06)",borderRadius:12}}><div style={sub}>{t.toUpperCase()}</div><div style={{fontSize:20,fontWeight:900}}>{v}</div></div>}
function btn(primary:boolean):React.CSSProperties{return {border:"1px solid rgba(255,255,255,.1)",background:primary?"rgba(181,123,255,.1)":"rgba(255,255,255,.04)",color:primary?"#d3b6ff":"#aaa",borderRadius:9,padding:"8px 10px",fontSize:9,fontWeight:850,cursor:"pointer"}}
