"use client";
import {useCallback,useEffect,useState} from "react";
type E={id:string;evidence_key:string;claim:string;value_text:string|null;source_url:string|null;confidence:number;excerpt:string|null};
type H={id:string;company_name:string|null;domain:string|null;segment_key:string;status:string;hypothesis:string;audience_angle:string;pain_statement:string;value_proposition:string;proof_requirements:string[];confidence:number;generator:string;evidence:E[]};
type D={aiConfigured:boolean;model:string;strategyVersion:string;counts:{queued:number;processing:number;completed:number;failed:number;proposed:number;approved:number};hypotheses:H[]};
export default function ResearchStrategyControlTower(){
 const[d,setD]=useState<D|null>(null),[busy,setBusy]=useState(""),[err,setErr]=useState(""),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch("/api/outbound/v3/research",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error||"Load failed");setD(j)}catch(e){setErr(e instanceof Error?e.message:"Load failed")}},[]);
 useEffect(()=>{void load()},[load]);
 async function post(p:any,key:string){setBusy(key);setErr("");setMsg("");try{const r=await fetch("/api/outbound/v3/research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(p)});const j=await r.json();if(!r.ok)throw new Error(j?.error||"Action failed");setMsg("Research aktualisiert.");await load()}catch(e){setErr(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}}
 async function review(h:H,dn:"approved"|"rejected"){const reason=window.prompt(dn==="approved"?"Warum ist die Strategie freigabefähig?":"Warum ablehnen?","Evidence geprüft");if(reason)await post({action:"review",hypothesisId:h.id,decision:dn,reason},"r"+h.id)}
 return <section style={{maxWidth:1540,margin:"0 auto 18px",padding:"0 28px"}}><div style={{border:"1px solid rgba(126,215,255,.16)",background:"rgba(8,13,12,.94)",borderRadius:24,padding:20}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><div style={{fontSize:10,fontWeight:900,letterSpacing:".12em",color:"#9fdbff"}}>M7 · RESEARCH + STRATEGY</div><h2 style={{fontSize:24,margin:"7px 0 6px"}}>Evidence-backed Research & Hypotheses</h2><p style={{fontSize:12,color:"#89958e",margin:0,maxWidth:900}}>Jede Firmenaussage bleibt an Quelle, Beobachtungszeit und Confidence gebunden. Hypothesen sind Tests, keine erfundenen Fakten.</p></div><div style={{display:"flex",gap:6}}><span style={pill}>AI: {d?.aiConfigured?"API":"Fallback"}</span><span style={pill}>Model: {d?.model||"…"}</span></div></div>
  {err&&<div style={{fontSize:10,color:"#ffb3b3",marginTop:10}}>{err}</div>}{msg&&<div style={{fontSize:10,color:"#8be9b2",marginTop:10}}>{msg}</div>}
  <div style={stats}><Stat t="Queued" v={d?.counts.queued||0}/><Stat t="Processing" v={d?.counts.processing||0}/><Stat t="Completed" v={d?.counts.completed||0}/><Stat t="Hypothesen offen" v={d?.counts.proposed||0}/></div>
  <div style={{display:"flex",gap:8,marginTop:14}}><button disabled={!!busy} style={btn(true)} onClick={()=>void post({action:"seed"},"seed")}>Research Queue füllen</button><button disabled={!!busy} style={btn(false)} onClick={()=>void post({action:"process"},"proc")}>Jetzt verarbeiten</button></div>
  <div style={box}><div style={title}>STRATEGIE-HYPOTHESEN</div>{(d?.hypotheses||[]).length?(d?.hypotheses||[]).map(h=><div key={h.id} style={row}><div style={{flex:1}}><div><b>{h.company_name||h.domain||"Firma"}</b> <span style={{fontSize:9,color:h.status==="approved"?"#8be9b2":"#d9c78b"}}>{h.status.toUpperCase()}</span> <span style={sub}>{Math.round(h.confidence*100)}%</span></div><div style={{fontSize:10,color:"#dce6df",marginTop:6}}>{h.hypothesis}</div><div style={sub}>{h.pain_statement}</div><div style={{marginTop:7,display:"flex",gap:5,flexWrap:"wrap"}}>{h.evidence.map(e=><a key={e.id} href={e.source_url||undefined} target="_blank" rel="noreferrer" style={{fontSize:8,color:"#8edfff",textDecoration:"none",border:"1px solid rgba(142,223,255,.15)",padding:"4px 6px",borderRadius:999}}>{e.evidence_key} · {Math.round(e.confidence*100)}%</a>)}</div></div>{h.status==="proposed"&&<div style={{display:"flex",gap:6}}><button disabled={!!busy} style={btn(true)} onClick={()=>void review(h,"approved")}>Freigeben</button><button disabled={!!busy} style={btn(false)} onClick={()=>void review(h,"rejected")}>Ablehnen</button></div>}</div>):<div style={sub}>Noch keine Einträge.</div>}</div>
 </div></section>
}
const pill:React.CSSProperties={fontSize:9,padding:"7px 9px",border:"1px solid rgba(255,255,255,.08)",borderRadius:999,color:"#aab7b0"};
const stats:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:10,marginTop:18};
const row:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:12,padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.05)",fontSize:10};
const sub:React.CSSProperties={fontSize:9,color:"#7f8b84",lineHeight:1.45,marginTop:3};
const box:React.CSSProperties={marginTop:12,border:"1px solid rgba(255,255,255,.07)",borderRadius:14,padding:12};
const title:React.CSSProperties={fontSize:9,fontWeight:900,color:"#78847d",marginBottom:6};
function Stat({t,v}:{t:string;v:number}){return <div style={{padding:12,border:"1px solid rgba(255,255,255,.06)",borderRadius:12}}><div style={sub}>{t.toUpperCase()}</div><div style={{fontSize:20,fontWeight:900}}>{v}</div></div>}
function btn(primary:boolean):React.CSSProperties{return {border:"1px solid rgba(255,255,255,.1)",background:primary?"rgba(126,215,255,.1)":"rgba(255,255,255,.04)",color:primary?"#a8e3ff":"#aaa",borderRadius:9,padding:"8px 10px",fontSize:9,fontWeight:850,cursor:"pointer"}}
