import { decodeOAuthState } from "@/lib/oauth-state";
import { readState, writeState } from "@/lib/db";
import { getSecret, setSecret } from "@/lib/secrets";

export async function GET(request:Request){
 const url=new URL(request.url);const code=url.searchParams.get("code");const stateRaw=url.searchParams.get("state");
 try{
  if(!code||!stateRaw)throw new Error("OAuth Code/State fehlt.");const state=decodeOAuthState(stateRaw);if(state.provider!=="microsoft")throw new Error("Falscher OAuth Provider.");
  const clientId=process.env.MICROSOFT_CLIENT_ID||await getSecret("microsoft_client_id");const clientSecret=process.env.MICROSOFT_CLIENT_SECRET||await getSecret("microsoft_client_secret");if(!clientId||!clientSecret)throw new Error("Microsoft OAuth Credentials fehlen.");
  const base=process.env.NEXT_PUBLIC_APP_URL||url.origin;const body=new URLSearchParams({client_id:clientId,client_secret:clientSecret,code,redirect_uri:`${base}/api/oauth/microsoft/callback`,grant_type:"authorization_code",scope:"openid profile email offline_access User.Read Mail.Send Mail.Read"});
  const tokenResponse=await fetch("https://login.microsoftonline.com/common/oauth2/v2.0/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});if(!tokenResponse.ok)throw new Error(`Microsoft Token Exchange fehlgeschlagen (${tokenResponse.status}).`);const token=await tokenResponse.json() as {access_token?:string;refresh_token?:string};if(!token.access_token)throw new Error("Microsoft Access Token fehlt.");
  const profileResponse=await fetch("https://graph.microsoft.com/v1.0/me?$select=displayName,mail,userPrincipalName",{headers:{Authorization:`Bearer ${token.access_token}`}});if(!profileResponse.ok)throw new Error("Microsoft Profil konnte nicht gelesen werden.");const profile=await profileResponse.json() as {displayName?:string;mail?:string;userPrincipalName?:string};const email=profile.mail||profile.userPrincipalName;if(!email)throw new Error("Microsoft Mailbox E-Mail fehlt.");
  const raw=await getSecret("mailbox_credentials_json").catch(()=>"");let list:Array<Record<string,unknown>>=[];try{list=raw?JSON.parse(raw):[]}catch{}const existing=list.find(x=>x.id===state.mailboxId) as Record<string,unknown>|undefined;const name=state.name||profile.displayName||String(existing?.name||email);const credential={...(existing||{}),id:state.mailboxId,provider:"microsoft",email,name,refreshToken:token.refresh_token||existing?.refreshToken,accessToken:token.refresh_token?undefined:token.access_token};const next=[...list.filter(x=>x.id!==state.mailboxId),credential];await setSecret("mailbox_credentials_json",JSON.stringify(next));
  const row=await readState().catch(()=>null);const current=(row?.payload||{}) as {mailboxes?:Array<Record<string,unknown>>};const mailboxes=current.mailboxes||[];const previous=mailboxes.find(x=>String(x.id)===state.mailboxId);const mailbox={...(previous||{}),id:state.mailboxId,name,email,provider:"Microsoft",dailyLimit:Number(previous?.dailyLimit||5),sentToday:Number(previous?.sentToday||0),warmupDay:Number(previous?.warmupDay||1),health:Number(previous?.health||60),enabled:true,spf:Boolean(previous?.spf),dkim:Boolean(previous?.dkim),dmarc:Boolean(previous?.dmarc)};await writeState({...current,mailboxes:[...mailboxes.filter(x=>String(x.id)!==state.mailboxId),mailbox]});
  return Response.redirect(`${base}/?oauth=microsoft-connected`);
 }catch(error){return Response.json({error:error instanceof Error?error.message:"Microsoft OAuth fehlgeschlagen."},{status:400})}
}
