import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const BA_BASE="https://rest.arbeitsagentur.de/jobboerse/jobsuche-service";
const BA_KEY="jobboerse-jobsuche";
const TARGET=100;
const TERMS=["Pflegedienst Pflegefachkraft","ambulante Pflege Pflegefachkraft","Sozialstation Pflegefachkraft","Intensivpflege Pflegefachkraft","häusliche Krankenpflege","ambulanter Pflegedienst","Pflegedienstleitung ambulant","Pflegefachkraft ambulant","mobiler Pflegedienst","außerklinische Intensivpflege","Pflege zuhause Pflegefachkraft","ambulante Krankenpflege"];
const DAYS=[30,60,100];
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-dg-pflege-secret","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Cache-Control":"no-store","Content-Type":"application/json; charset=utf-8"};
const STAFF=/(randstad|adecco|manpower|tempton|persona service|personaservice|pluss|akut|avanti|piening|unique personal|in care|incare|all\.medi|medwing|pacura|felten|iperdimed|zeitarbeit|arbeitnehmerüberlass|arbeitnehmeruberlass|personaldienst|personalvermittlung|staffing|leiharbeit|recruiting agentur|personalmanagement|personalservice|arbeitsvermittlung)/i;
const BIG=/(universitätsklin|universitaetsklin|universitätsmedizin|klinikum|\bklinik\b|krankenhaus|charit[eé]|helios|asklepios|sana klin|korian|alloheim|caritas|diakonie|deutsches rotes kreuz|\bdrk\b|\bbrk\b|arbeiterwohlfahrt|\bawo\b|johanniter|malteser|lebenshilfe|deutsche fachpflege|renafan|advita|aiutanda|compassio|dorea|emeis|pro seniore|kursana|azurit|münchenstift|munchenstift|landkreis|stadtverwaltung|bundeswehr|holding|konzern|bundesweit|zentrale geschäftsführung|zentrale geschaeftsfuehrung)/i;
const INPATIENT=/(pflegeheim|altenheim|seniorenheim|seniorenzentrum|seniorenresidenz|pflegezentrum|pflegewohn|wohnstift|wohnpark|stationäre pflege|stationaere pflege|tagespflege|hospiz)/i;
const AMB=/(pflegedienst|ambulant|sozialstation|häusliche pflege|haeusliche pflege|häusliche krankenpflege|haeusliche krankenpflege|mobile pflege|mobiler pflege|pflegeteam|pflege zuhause|pflege zu hause)/i;
const INTENSIVE=/(intensivpflege|1:1 pflege|außerklinische intensiv|ausserklinische intensiv|beatmungspflege)/i;
const PORTAL=/(arbeitsagentur\.de|jobboerse|jobbörse|indeed\.|stepstone\.|meinestadt\.|kimeta\.|adzuna\.|talent\.com|xing\.com\/jobs|linkedin\.com\/jobs|joblift\.|jobrapido\.)/i;
const BAD_MAIL=/(arbeitsagentur\.de|jobcenter\.|indeed\.|stepstone\.|meinestadt\.|kimeta\.|adzuna\.|talent\.com|joblift\.|jobrapido\.)$/i;
const reply=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:CORS});
function day(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Berlin",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`;}
function norm(v:unknown){return String(v??"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim();}
function hash(v:string){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
function strings(v:unknown,out:string[]=[]):string[]{if(typeof v==="string")out.push(v);else if(Array.isArray(v))for(const x of v)strings(x,out);else if(v&&typeof v==="object")for(const x of Object.values(v as Record<string,unknown>))strings(x,out);return out;}
function first(o:Record<string,unknown>,ks:string[]){for(const k of ks){const v=o?.[k];if(typeof v==="string"&&v.trim())return v.trim();}return"";}
function ms(v:unknown){const x=Date.parse(String(v||""));return Number.isFinite(x)?x:0;}
function excluded(name:string,text=""){const v=`${name} ${text}`;return !name||STAFF.test(v)||BIG.test(v)||INPATIENT.test(name);}
function cat(name:string,text:string){const v=`${name} ${text}`;if(INTENSIVE.test(v))return"intensive_care";if(AMB.test(v)&&!INPATIENT.test(v))return"ambulatory_care";return"";}
function mail(v:string){const e=String(v||"").trim().toLowerCase().replace(/^mailto:/,"").replace(/[>,;.)]+$/g,"");if(!/^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/i.test(e)||/^(no-?reply|noreply|donotreply)@/i.test(e))return"";return BAD_MAIL.test(e.split("@")[1]||"")?"":e;}
function mailText(t:string){for(const x of t.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]){const e=mail(x);if(e)return e;}return"";}
function phone(t:string){for(const m of t.matchAll(/(?:Tel\.?|Telefon|Mobil|Handy|Phone|href=["']tel:)\s*[:=]?\s*["']?((?:\+49|0049|0)[\d\s()\/-]{7,20})/gi)){let p=m[1].replace(/[^\d+]/g,"");if(p.startsWith("0049"))p=`+49${p.slice(4)}`;const d=p.replace(/\D/g,"");if(p.startsWith("+49")&&d.length>=11&&d.length<=14)return`+${d}`;if(d.startsWith("0")&&d.length>=9&&d.length<=13)return d;}return"";}
function person(t:string){const p=t.replace(/<[^>]+>/g," ").replace(/\s+/g," ");for(const r of [/(?:Geschäftsführer(?:in)?|Inhaber(?:in)?|Pflegedienstleitung|PDL|Ansprechpartner(?:in)?|Kontaktperson)\s*:?\s*(?:Herrn?|Frau)?\s*([A-ZÄÖÜ][A-Za-zÄÖÜäöüß'’.-]+\s+[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'’.-]+)/g,/(?:Herr|Frau)\s+([A-ZÄÖÜ][A-Za-zÄÖÜäöüß'’.-]+\s+[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'’.-]+)/g])for(const m of p.matchAll(r)){const n=m[1].trim();if(n.length<61&&!/(Pflege|Team|Bewohner|Menschen|Kontakt|Bewerbung)/i.test(n))return n;}return"";}
function state(v:string){const t=norm(v),map:Array<[RegExp,string]>=[[/baden.wurttemberg|baden_wuerttemberg/,"Baden-Württemberg"],[/bayern/,"Bayern"],[/berlin/,"Berlin"],[/brandenburg/,"Brandenburg"],[/bremen/,"Bremen"],[/hamburg/,"Hamburg"],[/hessen/,"Hessen"],[/mecklenburg/,"Mecklenburg-Vorpommern"],[/niedersachsen/,"Niedersachsen"],[/nordrhein|nrw/,"Nordrhein-Westfalen"],[/rheinland.pfalz/,"Rheinland-Pfalz"],[/saarland/,"Saarland"],[/sachsen.anhalt/,"Sachsen-Anhalt"],[/sachsen/,"Sachsen"],[/schleswig.holstein/,"Schleswig-Holstein"],[/thuringen/,"Thüringen"]];for(const[r,l]of map)if(r.test(t))return l;return"Unbekannt";}
function loc(s:Record<string,unknown>,d:Record<string,unknown>){let a:Record<string,unknown>={};const dl=Array.isArray(d.stellenlokationen)?d.stellenlokationen as Record<string,unknown>[]:[],sl=Array.isArray(s.stellenlokationen)?s.stellenlokationen as Record<string,unknown>[]:[];if(dl[0]?.adresse&&typeof dl[0].adresse==="object")a=dl[0].adresse as Record<string,unknown>;else if(sl[0]?.adresse&&typeof sl[0].adresse==="object")a=sl[0].adresse as Record<string,unknown>;else if(d.arbeitgeberAdresse&&typeof d.arbeitgeberAdresse==="object")a=d.arbeitgeberAdresse as Record<string,unknown>;const street=first(a,["strasseHausnummer","strasse","straße"]),plz=String(a.plz||a.postleitzahl||""),city=first(a,["ort","stadt","city"]),region=first(a,["region","bundesland"]),address=[street,[plz,city].filter(Boolean).join(" "),region].filter(Boolean).join(", ");return{city,address,state:state(`${region} ${address}`)};}
function site(d:Record<string,unknown>,email:string){for(const x of strings(d))if(/^https?:\/\//i.test(x))try{const u=new URL(x);if(!PORTAL.test(u.hostname+u.pathname))return`${u.protocol}//${u.hostname}`;}catch{}const dm=email.split("@")[1]||"";return dm&&!BAD_MAIL.test(dm)?`https://${dm}`:"";}
async function fetchText(url:string){const c=new AbortController(),tm=setTimeout(()=>c.abort(),3500);try{const r=await fetch(url,{redirect:"follow",signal:c.signal,headers:{"User-Agent":"Mozilla/5.0 DigitaleGewinnerPflegeRadar/2.1"}});if(!r.ok||PORTAL.test(r.url))return{url:r.url||url,text:""};return{url:r.url,text:(await r.text()).slice(0,140000)};}catch{return{url,text:""};}finally{clearTimeout(tm);}}
async function inspect(website:string,needEmail:boolean){if(!website)return{url:"",email:"",phone:"",person:"",finding:"Keine eigene Website sicher erkannt",opp:94,career:false,form:false};const home=await fetchText(website);let text=home.text,email=mailText(text),ph=phone(text),per=person(text);if(needEmail&&!email&&home.url)try{const u=new URL(home.url).origin,x=await fetchText(`${u}/kontakt`);text+=`\n${x.text}`;email||=mailText(text);ph||=phone(text);per||=person(text);}catch{}const career=/(karriere|stellenangebote|jobs|bewerben|offene stellen)/i.test(text),form=/<form\b/i.test(text);let finding="Online-Auftritt mit Recruiting-Potenzial",opp=70;if(!text){finding="Website nicht zuverlässig erreichbar";opp=88;}else if(!career){finding="Kein klarer Karriere-/Bewerberweg erkannt";opp=92;}else if(!form){finding="Kein direktes Bewerbungsformular erkannt";opp=84;}return{url:home.url||website,email,phone:ph,person:per,finding,opp,career,form};}
function cfg(){const url=Deno.env.get("SUPABASE_URL")||"",key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!key)throw new Error("Supabase env missing");return{url,key};}
async function db(path:string,init:RequestInit={}){const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(init.headers||{})}});if(!r.ok)throw new Error(`DB ${r.status}: ${await r.text()}`);const t=await r.text();return t?JSON.parse(t):null;}
async function control(){const x=await db("pflege_email_runtime_control?id=eq.true&select=enabled,secret,target_count,cursor,cursor_day&limit=1") as any[];return x[0];}
async function patchControl(body:Record<string,unknown>){await db("pflege_email_runtime_control?id=eq.true",{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(body)});}
async function queue(d:string){return await db(`pflege_email_outreach?lead_date=eq.${d}&status=neq.historical&select=id,rank,lead_key,email,lead&order=rank.asc&limit=200`) as any[];}
function jobTitle(l:Record<string,unknown>){const refs=Array.isArray(l.jobReferences)?l.jobReferences as any[]:[],sig=l.signals&&typeof l.signals==="object"?l.signals as any:{};return String(refs[0]?.title||sig.jobTitles?.[0]||"Pflegefachkräfte");}
function draft(l:Record<string,unknown>){const company=String(l.name||"Ihrem Pflegedienst"),p=String(l.contactPerson||""),title=jobTitle(l),sig=l.signals&&typeof l.signals==="object"?l.signals as any:{},finding=String(sig.websiteAudit?.finding||""),subject=`${company}: kurze Idee zu ${title}`.slice(0,145),greeting=p?`Guten Tag ${p},`:"Guten Tag,",trigger=Number(sig.jobCount||0)>1?`ich habe gesehen, dass Sie aktuell mehrere Pflege-Stellen besetzen – unter anderem ${title}.`:`ich habe gesehen, dass Sie aktuell ${title} suchen.`,web=finding?`\nBeim Blick auf Ihren Online-Auftritt ist mir außerdem aufgefallen: ${finding}.\n`:"\n",body=`${greeting}\n\n${trigger}${web}\nIch baue für Pflegedienste ein kompaktes Websystem, das Website, Bewerber- und Kundenanfragen, Terminbuchung, Automationen und ein Admin-Dashboard zusammenbringt.\n\nNormalerweise liegt so ein System bei 5.000 €. Aktuell biete ich es für 750 € einmalig + 79 €/Monat an, monatlich kündbar.\n\nIch kann Ihnen für ${company} vorab kostenlos einen individuellen Entwurf erstellen. Wenn er Ihnen nicht gefällt, kostet es nichts. Bei Interesse reicht ein kurzes „Ja“ – dann schicke ich Ihnen den Entwurf innerhalb von 48 Stunden.\n\nBeste Grüße\nRaphael Hermann`;return{subject,body};}
function row(d:string,rank:number,key:string,l:Record<string,unknown>){const x=draft(l);return{lead_date:d,rank,lead_key:key,email:mail(String(l.email||"")),subject:x.subject,body:x.body,status:"draft",lead:l};}
async function insert(rows:any[]){if(rows.length)await db("pflege_email_outreach?on_conflict=lead_key",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify(rows)});}
function eligible(l:Record<string,unknown>){const c=String(l.category||""),crm=l.crm&&typeof l.crm==="object"?l.crm as any:{};return crm.doNotContact!==true&&!!mail(String(l.email||""))&&["ambulatory_care","intensive_care"].includes(c)&&!excluded(String(l.name||""),JSON.stringify(l.signals||{}))&&Number(l.score||0)>=78;}
async function seedDaily(d:string,target:number){const before=await queue(d);if(before.length>=target)return 0;const daily=await db(`pflege_daily_leads?lead_date=eq.${d}&select=rank,lead_key,lead&order=rank.asc&limit=300`) as any[],c=daily.filter(x=>eligible(x.lead)).sort((a,b)=>Number(b.lead.score||0)-Number(a.lead.score||0)),def=target-before.length;await insert(c.slice(0,def).map((x,i)=>row(d,before.length+i+1,x.lead_key,x.lead)));return(Math.max(0,(await queue(d)).length-before.length));}
async function ba(url:string){const c=new AbortController(),tm=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{headers:{"X-API-Key":BA_KEY,Accept:"application/json"},signal:c.signal});if(!r.ok)throw new Error(`BA ${r.status}`);return await r.json();}finally{clearTimeout(tm);}}
async function detail(ref:string){try{return await ba(`${BA_BASE}/pc/v4/jobdetails/${encodeURIComponent(btoa(ref))}`) as Record<string,unknown>;}catch{return null;}}
async function build(ref:string,s:Record<string,unknown>,d:Record<string,unknown>){const name=String(d.firma||d.arbeitgeber||s.firma||s.arbeitgeber||"").trim(),text=strings(d).join("\n");if(excluded(name,text))return null;const category=cat(name,`${String(s.stellenangebotsTitel||s.beruf||s.hauptberuf||"")} ${text}`);if(!category)return null;const l=loc(s,d);if(l.state==="Unbekannt")return null;let email=mailText(text),website=site(d,email),ph=phone(text),per=person(text);const a=await inspect(website,!email);email=mail(email||a.email);ph||=a.phone;per||=a.person;if(!email)return null;const title=first(d,["stellenangebotsTitel","titel","beruf","hauptberuf"])||String(s.stellenangebotsTitel||s.beruf||"Pflegefachkraft"),pub=first(d,["datumErsteVeroeffentlichung","aktuelleVeroeffentlichungsdatum","veroeffentlichungsdatum"])||String((s.veroeffentlichungszeitraum as any)?.von||""),upd=first(d,["aenderungsdatum","modifikationsTimestamp","lastUpdatedAt"])||String(s.aenderungsdatum||pub),age=Math.max(0,Math.floor((Date.now()-Math.max(ms(upd),ms(pub),Date.now()-30*86400000))/86400000)),fresh=age<=7?100:age<=14?95:88,fit=category==="intensive_care"?100:98,access=Math.min(100,90+(ph?4:0)+(per?3:0)),score=Math.min(99,Math.round(94*.32+fit*.27+access*.21+fresh*.1+a.opp*.1));if(score<80)return null;const lead={id:`pflege-email-${hash(norm(name))}`,name,address:l.address,federalState:l.state,city:l.city,website:a.url||website,phone:ph,email,contactPerson:per,category,score,fitScore:fit,opportunityScore:a.opp,needScore:94,accessibilityScore:access,organizationRisk:"low",tier:"1A",callPriority:"1A",confidence:.96,recommendedOffer:"Premium-Websystem für Pflegedienste: Website + Bewerber/Kunden-Funnel + Terminbuchung + Automationen + Admin-Dashboard",pitch:`Aktive Stelle ${title} bestätigt. ${a.finding}.`,summary:`Aktiver Pflege-Personalbedarf · öffentliche Geschäfts-E-Mail · ${category==="intensive_care"?"Intensivpflege":"ambulanter Pflegedienst"}.`,status:"new",sourceType:"pflege-email-outreach-v2",scoringVersion:"pflege-email-1a-v2",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),jobReferences:[{title,referenceNumber:ref,url:`https://www.arbeitsagentur.de/jobsuche/jobdetail/${ref}`,publishingStartDate:pub||null,lastUpdatedAt:upd||pub||null}],signals:{hiringStatus:"confirmed",jobCount:1,jobTitles:[title],websiteAudit:{ok:!!a.url,career:a.career,form:a.form,finding:a.finding,opportunity:a.opp},points:["Aktive Pflege-Stelle bestätigt","Öffentliche Geschäfts-E-Mail verifiziert",a.finding,per?`Ansprechpartner: ${per}`:"Direkter Betriebskontakt"]}};return{key:`${norm(name)}|${l.state}`,lead};}
async function oneTask(d:string,target:number,cursor:number){const term=TERMS[cursor%TERMS.length],page=Math.floor(cursor/TERMS.length)%5+1,days=DAYS[Math.floor(cursor/(TERMS.length*5))%DAYS.length],q=new URLSearchParams({was:term,page:String(page),size:"100",veroeffentlichtseit:String(days),angebotsart:"1",zeitarbeit:"false"}),data=await ba(`${BA_BASE}/pc/v6/jobs?${q}`) as any,jobs=(Array.isArray(data.ergebnisliste)?data.ergebnisliste:[]) as Record<string,unknown>[],filtered=jobs.filter(j=>{const n=String(j.firma||j.arbeitgeber||""),seed=`${n} ${String(j.stellenangebotsTitel||j.beruf||j.hauptberuf||"")}`;return n&&!excluded(n,seed)&&(AMB.test(seed)||INTENSIVE.test(seed));}).slice(0,18);let ready=await queue(d),added=0;for(let i=0;i<filtered.length&&ready.length<target;i+=6){const b=filtered.slice(i,i+6),details=await Promise.all(b.map(j=>detail(String(j.referenznummer||j.refnr||"")))),built=await Promise.all(b.map((j,k)=>details[k]?build(String(j.referenznummer||j.refnr||""),j,details[k] as Record<string,unknown>):Promise.resolve(null))),fresh:any[]=[];const local=new Set(ready.map(x=>x.lead_key));for(const x of built)if(x&&!local.has(x.key)){local.add(x.key);fresh.push(x);}if(fresh.length){const deficit=target-ready.length,before=ready.length;await insert(fresh.slice(0,deficit).map((x,k)=>row(d,ready.length+k+1,x.key,x.lead)));ready=await queue(d);added+=Math.max(0,ready.length-before);}}return{added,ready:ready.length,task:{term,page,days,raw:jobs.length,candidates:filtered.length}};}
async function sync(){return await db("rpc/sync_pflege_email_outreach_to_sales",{method:"POST",body:"{}"});}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});const d=day();try{let c=await control();if(!c?.enabled)return reply({ok:false,disabled:true,d},503);if(!c.secret||req.headers.get("x-dg-pflege-secret")!==c.secret)return reply({error:"Unauthorized"},401);let cursor=Number(c.cursor||0);if(c.cursor_day!==d){cursor=0;await patchControl({cursor:0,cursor_day:d,last_error:""});}const target=Math.max(1,Math.min(200,Number(c.target_count||TARGET))),seeded=await seedDaily(d,target);let ready=(await queue(d)).length,result={added:0,ready,task:null as any};if(ready<target)result=await oneTask(d,target,cursor);ready=result.ready;await patchControl({cursor:cursor+1,cursor_day:d,last_run_at:new Date().toISOString(),last_error:""});const sales=await sync();return reply({ok:ready>=target,date:d,target,ready,deficit:Math.max(0,target-ready),seeded,discovered:result.added,task:result.task,nextCursor:cursor+1,sync:sales},ready>=target?200:206);}catch(e){try{await patchControl({last_run_at:new Date().toISOString(),last_error:String((e as Error)?.message||e).slice(0,500)});}catch{}return reply({ok:false,date:d,error:String((e as Error)?.message||e)},500);}});
